/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class FormsPreEncomendas extends javax.swing.JFrame {

    /**
     * Creates new form FormsPreEncomendas
     */
    static String dbName = "daquinta_teste"; //Nome do Banco criado
    
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
    
    java.util.Date date = new java.util.Date();
    
    Calendar cal = Calendar.getInstance();
    Calendar calUk = Calendar.getInstance(Locale.UK);  
    
    Calendar Datam;  
    Integer getMonth = 1;
    Integer ano = date.getYear()+1900;
    
    Connection con, con2;
    Statement stmt, stmt2;
    ResultSet rs, rsProdutos;
    int curRow = 0;
    int IDs = 1;
    DB conDB = new DB();
    boolean editar = false, criarnovo=false, variavelControlNomeProdutos=false;
    
    int restaurante;
    
    int iA=0, iB=0, iC=0, iD=0, iE=0, iF=0, iG=0, iH=0;
    int mA=0, mB=0, mC=0, mD=0, mE=0, mF=0, mG=0, mH=0;
    int iJ=0;
    Integer restauranteSelected;
    
    Integer produtoselectedA, produtoselectedB, produtoselectedC, produtoselectedD, produtoselectedE, produtoselectedF, produtoselectedG, produtoselectedH;
    Integer messelectedA, messelectedB, messelectedC, messelectedD, messelectedE, messelectedF, messelectedG, messelectedH;
   
    //int jan=5,fev=5,mar=5,abr=5,mai=5,jun=5,jul=5,ago=5,set=5,out=5,nov=5,dez=5;
    
    public FormsPreEncomendas() {
        initComponents();
        
        
       /* if ( (date.getMonth()+1) == 1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if ( (date.getMonth()+1) == 10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if ( (date.getMonth()+1) == 11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if ( (date.getMonth()+1) == 12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        
        
                
        produtoselectedA = jComboBoxProduto1.getSelectedIndex()+2;
        jComboBoxAno.setSelectedIndex(ano-2011);
        
        DoConnect();
        setLocationRelativeTo(null);
        
        jLabelData.setText(dateFormat.format(date).toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxProduto1 = new javax.swing.JComboBox();
        jTextRestauranteA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextRestauranteB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxProduto2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxProduto3 = new javax.swing.JComboBox();
        jTextRestauranteC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBoxProduto4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextRestauranteD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxProduto5 = new javax.swing.JComboBox();
        jTextRestauranteE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jComboBox1Mes = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2Mes = new javax.swing.JComboBox();
        jComboBox4Mes = new javax.swing.JComboBox();
        jComboBox3Mes = new javax.swing.JComboBox();
        jComboBox5Mes = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextRestauranteF = new javax.swing.JTextField();
        jComboBoxProduto6 = new javax.swing.JComboBox();
        jComboBox6Mes = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextRestauranteG = new javax.swing.JTextField();
        jComboBoxProduto7 = new javax.swing.JComboBox();
        jComboBox7Mes = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox8Mes = new javax.swing.JComboBox();
        jComboBoxProduto8 = new javax.swing.JComboBox();
        jTextRestauranteH = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxAno = new javax.swing.JComboBox();
        jBtnPesquisa = new javax.swing.JButton();
        jComboBox9Mes = new javax.swing.JComboBox();
        jComboBoxProduto9 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pre-Encomendas");
        setName("Pré-Encomendas");
        setResizable(false);

        jLabel1.setText("Centro Social de Palmela");

        jComboBoxProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto1ActionPerformed(evt);
            }
        });

        jTextRestauranteA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteA.setText("0");
        jTextRestauranteA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteAKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Restaurante");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Produto");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Quantidade");

        jLabel5.setText("kg");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextRestauranteB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteB.setText("0");
        jTextRestauranteB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteBKeyPressed(evt);
            }
        });

        jLabel6.setText("kg");

        jComboBoxProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Restaurante “O Parque”");

        jLabel8.setText("Restaurante “Champanheria”");

        jComboBoxProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto3ActionPerformed(evt);
            }
        });

        jTextRestauranteC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteC.setText("0");
        jTextRestauranteC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteCKeyPressed(evt);
            }
        });

        jLabel9.setText("kg");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBoxProduto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Restaurante “Três15Dias”");

        jTextRestauranteD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteD.setText("0");
        jTextRestauranteD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteDKeyPressed(evt);
            }
        });

        jLabel11.setText("kg");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Restaurante “D. Isilda”");

        jComboBoxProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto5ActionPerformed(evt);
            }
        });

        jTextRestauranteE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteE.setText("0");
        jTextRestauranteE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteEKeyPressed(evt);
            }
        });

        jLabel13.setText("kg");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setMaximumSize(new java.awt.Dimension(111, 41));
        btnCancel.setMinimumSize(new java.awt.Dimension(111, 41));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/77.png"))); // NOI18N
        jLabel14.setText("Pré-Encomenda");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelData.setText("88-88.8888");

        jLabel15.setText("DATA:");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/10.png"))); // NOI18N
        jButton11.setText("Listagem");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBox1Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox1Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1MesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setText("Mês");

        jComboBox2Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox2Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2MesActionPerformed(evt);
            }
        });

        jComboBox4Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox4Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4MesActionPerformed(evt);
            }
        });

        jComboBox3Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox3Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3MesActionPerformed(evt);
            }
        });

        jComboBox5Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox5Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5MesActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel18.setText("kg");

        jTextRestauranteF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteF.setText("0");
        jTextRestauranteF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteFKeyPressed(evt);
            }
        });

        jComboBoxProduto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto6ActionPerformed(evt);
            }
        });

        jComboBox6Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox6Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6MesActionPerformed(evt);
            }
        });

        jLabel19.setText("Restaurante “Malagueta”");

        jLabel20.setText("kg");

        jTextRestauranteG.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteG.setText("0");
        jTextRestauranteG.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteGKeyPressed(evt);
            }
        });

        jComboBoxProduto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto7ActionPerformed(evt);
            }
        });

        jComboBox7Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox7Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7MesActionPerformed(evt);
            }
        });

        jLabel21.setText("Vale dos Pintassilgos");

        jLabel22.setText("Santa Casa da Misericórdia");

        jComboBox8Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox8Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8MesActionPerformed(evt);
            }
        });

        jComboBoxProduto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto8ActionPerformed(evt);
            }
        });

        jTextRestauranteH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextRestauranteH.setText("0");
        jTextRestauranteH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRestauranteH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextRestauranteHKeyPressed(evt);
            }
        });

        jLabel23.setText("kg");

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015" }));

        jBtnPesquisa.setText("Pesquisa");
        jBtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaActionPerformed(evt);
            }
        });

        jComboBox9Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox9Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9MesActionPerformed(evt);
            }
        });

        jComboBoxProduto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto9ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Definir para todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox8Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox7Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox6Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox9Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jBtnPesquisa)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxProduto9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBoxProduto7, javax.swing.GroupLayout.Alignment.LEADING, 0, 186, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxProduto8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextRestauranteG)
                                            .addComponent(jTextRestauranteF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextRestauranteE, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextRestauranteD, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextRestauranteC, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextRestauranteB, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextRestauranteA, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextRestauranteH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelData)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox9Mes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProduto9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(jTextRestauranteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(jLabel6)
                    .addComponent(jTextRestauranteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton3)
                    .addComponent(jLabel9)
                    .addComponent(jTextRestauranteC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton4)
                    .addComponent(jLabel11)
                    .addComponent(jTextRestauranteD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton5)
                    .addComponent(jLabel13)
                    .addComponent(jTextRestauranteE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton6)
                    .addComponent(jLabel18)
                    .addComponent(jTextRestauranteF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton7)
                    .addComponent(jLabel20)
                    .addComponent(jTextRestauranteG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton8)
                    .addComponent(jLabel23)
                    .addComponent(jTextRestauranteH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPesquisa))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
        restaurante = 1;
        jButton1.setEnabled(false);
        String  produto=(String)jComboBoxProduto1.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteA.getText());
        
        String  mes=(String)jComboBox1Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        restaurante = 2;
        jButton2.setEnabled(false);
        String  produto=(String)jComboBoxProduto2.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteB.getText());
        
        String  mes=(String)jComboBox2Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        restaurante = 3;
           jButton3.setEnabled(false);
        String  produto=(String)jComboBoxProduto3.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteC.getText());
        
        String  mes=(String)jComboBox3Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        restaurante = 4;
           jButton4.setEnabled(false);
        String  produto=(String)jComboBoxProduto4.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteD.getText());
        
        String  mes=(String)jComboBox4Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        restaurante = 5;
           jButton5.setEnabled(false);
        String  produto=(String)jComboBoxProduto5.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteE.getText());
        
        String  mes=(String)jComboBox5Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         if ( jButton1.isEnabled()==true || jButton2.isEnabled()==true || jButton3.isEnabled()==true || jButton4.isEnabled()==true || jButton5.isEnabled()==true || jButton6.isEnabled()==true || jButton7.isEnabled()==true || jButton8.isEnabled()==true )  
                javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Contem Alterações que necessitam de ser salvas" );
        else closeApplication();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       ListaPreEncomendas preEnco = new ListaPreEncomendas();
       preEnco.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       restaurante = 6;
        String produto=(String)jComboBoxProduto5.getSelectedItem();
           jButton6.setEnabled(false);
        int quantidade=Integer.parseInt( jTextRestauranteE.getText());
        String  mes=(String)jComboBox5Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       restaurante = 7;
           jButton7.setEnabled(false);
        String  produto=(String)jComboBoxProduto7.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteH.getText());
        
        String  mes=(String)jComboBox7Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        restaurante = 8;
           jButton8.setEnabled(false);
        String  produto=(String)jComboBoxProduto8.getSelectedItem();
        
        int quantidade=Integer.parseInt( jTextRestauranteH.getText());
        
        String  mes=(String)jComboBox8Mes.getSelectedItem();
        int m=0;
        
        if (mes.equals("Janeiro")) m=1;
        if (mes.equals("Fevereiro")) m=2;
        if (mes.equals("Março")) m=3;
        if (mes.equals("Abril")) m=4;
        if (mes.equals("Maio")) m=5;
        if (mes.equals("Junho")) m=6;
        if (mes.equals("Julho")) m=7;
        if (mes.equals("Agosto")) m=8;
        if (mes.equals("Setembro")) m=9;
        if (mes.equals("Outubro")) m=10;
        if (mes.equals("Novembro")) m=11;
        if (mes.equals("Dezembro")) m=12;
                
        if (quantidade>=0)  conDB.AdicionarPreEncomenda(restaurante, produto, quantidade, m);
        else javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Quantidade tem que ser superior a 0(zero)" );
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox7MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7MesActionPerformed
        messelectedA = jComboBox7Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto7.getSelectedIndex()+1;
        restauranteSelected = 7;
        if (mG>0)  DoConnectA();
        mG++;
    }//GEN-LAST:event_jComboBox7MesActionPerformed

    private void jComboBox1MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1MesActionPerformed
       /* if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        
        //javax.swing.JOptionPane.showMessageDialog( FormsPreEncomendas.this, "Selecionou dez: " + dez );
        //jComboBoxProduto1.removeAllItems();
        messelectedA = jComboBox1Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto1.getSelectedIndex()+1;
        restauranteSelected = 1;
        if (mA>0)  
            DoConnectA();
        mA++;
    }//GEN-LAST:event_jComboBox1MesActionPerformed

    private void jBtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaActionPerformed
        // TODO add your handling code here:
        ano = Integer.parseInt((String) jComboBoxAno.getSelectedItem());
        messelectedA = 1;
        produtoselectedA = 1;
        jComboBoxProduto1.setSelectedIndex(0);
        jComboBoxProduto2.setSelectedIndex(0);
        jComboBoxProduto3.setSelectedIndex(0);
        jComboBoxProduto4.setSelectedIndex(0);;
        jComboBoxProduto5.setSelectedIndex(0); 
        jComboBoxProduto6.setSelectedIndex(0); 
        jComboBoxProduto7.setSelectedIndex(0);  
        jComboBoxProduto8.setSelectedIndex(0);
        jComboBoxProduto9.setSelectedIndex(0);
        jComboBox1Mes.setSelectedIndex(0);
        jComboBox2Mes.setSelectedIndex(0);
        jComboBox3Mes.setSelectedIndex(0);
        jComboBox4Mes.setSelectedIndex(0);;
        jComboBox5Mes.setSelectedIndex(0); 
        jComboBox6Mes.setSelectedIndex(0); 
        jComboBox7Mes.setSelectedIndex(0);  
        jComboBox8Mes.setSelectedIndex(0);
        jComboBox9Mes.setSelectedIndex(0);
        DoConnect();
    }//GEN-LAST:event_jBtnPesquisaActionPerformed

    private void jComboBox2MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2MesActionPerformed
       /* if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        messelectedA = jComboBox2Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto2.getSelectedIndex()+1;
        restauranteSelected = 2;
        //if (mB>0)  
            DoConnectA();
        //mB++;
    }//GEN-LAST:event_jComboBox2MesActionPerformed

    private void jComboBox3MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3MesActionPerformed
       /* if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        messelectedA = jComboBox3Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto3.getSelectedIndex()+1;
        restauranteSelected = 3;
        //if (mC>0)  
        DoConnectA();
        //mC++;
    }//GEN-LAST:event_jComboBox3MesActionPerformed

    private void jComboBox4MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4MesActionPerformed
        /*if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        messelectedA = jComboBox4Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto4.getSelectedIndex()+1;
        restauranteSelected = 4;
        //if (mD>0) 
        DoConnectA();
        //mD++;
    }//GEN-LAST:event_jComboBox4MesActionPerformed

    private void jComboBox5MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5MesActionPerformed
       /* if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        messelectedA = jComboBox5Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto5.getSelectedIndex()+1;
        restauranteSelected = 5;
        //if (mE>0)  
        DoConnectA();
        //mE++;
    }//GEN-LAST:event_jComboBox5MesActionPerformed

    private void jComboBox6MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6MesActionPerformed
       /* if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        messelectedA = jComboBox6Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto6.getSelectedIndex()+1;
        restauranteSelected = 6;
        //if (mF>0)  
        DoConnectA();
        //mF++;
    }//GEN-LAST:event_jComboBox6MesActionPerformed

    private void jComboBox8MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8MesActionPerformed
       /* if (jComboBox1Mes.getSelectedIndex()+1==1) jan=1;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==2) jan=5;fev=1;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==3) jan=5;fev=5;mar=1;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==4) jan=5;fev=5;mar=5;abr=1;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==5) jan=5;fev=5;mar=5;abr=5;mai=1;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==6) jan=5;fev=5;mar=5;abr=5;mai=5;jun=1;jul=5;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==7) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=1;ago=5;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==8) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=1;set=5;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==9) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=1;out=5;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==10) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=1;nov=5;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==11) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=1;dez=5;
        if (jComboBox1Mes.getSelectedIndex()+1==12) jan=5;fev=5;mar=5;abr=5;mai=5;jun=5;jul=5;ago=5;set=5;out=5;nov=5;dez=1;
        * 
        */
        messelectedA = jComboBox8Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto8.getSelectedIndex()+1;
        restauranteSelected = 8;
        //if (mH>0)  
        DoConnectA();
        //mH++;
    }//GEN-LAST:event_jComboBox8MesActionPerformed

    private void jComboBoxProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto1ActionPerformed
        messelectedA = jComboBox1Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto1.getSelectedIndex()+1;
        restauranteSelected = 1;
        if (iA>0)  DoConnectA();
        iA++;
    }//GEN-LAST:event_jComboBoxProduto1ActionPerformed

    private void jComboBoxProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto2ActionPerformed
        messelectedA = jComboBox2Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto2.getSelectedIndex()+1;
        restauranteSelected = 2;
        if (iB>0)  DoConnectA();
        iB++;
    }//GEN-LAST:event_jComboBoxProduto2ActionPerformed

    private void jComboBoxProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto3ActionPerformed
        messelectedA = jComboBox3Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto3.getSelectedIndex()+1;
        restauranteSelected = 3;
        if (iC>0)  DoConnectA();
        iC++;
    }//GEN-LAST:event_jComboBoxProduto3ActionPerformed

    private void jComboBoxProduto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto4ActionPerformed
        messelectedA = jComboBox4Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto4.getSelectedIndex()+1;
        restauranteSelected = 4;
        if (iD>0)  DoConnectA();
        iD++;
    }//GEN-LAST:event_jComboBoxProduto4ActionPerformed

    private void jComboBoxProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto5ActionPerformed
        messelectedA = jComboBox5Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto5.getSelectedIndex()+1;
        restauranteSelected = 5;
        if (iE>0)  DoConnectA();
        iE++;
    }//GEN-LAST:event_jComboBoxProduto5ActionPerformed

    private void jComboBoxProduto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto6ActionPerformed
        messelectedA = jComboBox6Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto6.getSelectedIndex()+1;
        restauranteSelected = 6;
        if (iF>0)  DoConnectA();
        iF++;
    }//GEN-LAST:event_jComboBoxProduto6ActionPerformed

    private void jComboBoxProduto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto7ActionPerformed
        messelectedA = jComboBox7Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto7.getSelectedIndex()+1;
        restauranteSelected = 7;
        if (iG>0)  DoConnectA();
        iG++;
    }//GEN-LAST:event_jComboBoxProduto7ActionPerformed

    private void jComboBoxProduto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto8ActionPerformed
        messelectedA = jComboBox8Mes.getSelectedIndex()+1;
        produtoselectedA = jComboBoxProduto8.getSelectedIndex()+1;
        restauranteSelected = 8;
        if (iH>0)  DoConnectA();
        iH++;
    }//GEN-LAST:event_jComboBoxProduto8ActionPerformed

    private void jComboBox9MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9MesActionPerformed
        if (jCheckBox1.isSelected()) {
            messelectedA = jComboBox9Mes.getSelectedIndex()+1;
            produtoselectedA = jComboBoxProduto9.getSelectedIndex()+1;
            jComboBoxProduto1.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto2.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto3.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto4.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto5.setSelectedIndex(produtoselectedA-1); 
            jComboBoxProduto6.setSelectedIndex(produtoselectedA-1); 
            jComboBoxProduto7.setSelectedIndex(produtoselectedA-1);  
            jComboBoxProduto8.setSelectedIndex(produtoselectedA-1);
            jComboBox1Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox2Mes.setSelectedIndex(messelectedA-1);
            jComboBox3Mes.setSelectedIndex(messelectedA-1);
            jComboBox4Mes.setSelectedIndex(messelectedA-1);
            jComboBox5Mes.setSelectedIndex(messelectedA-1); 
            jComboBox6Mes.setSelectedIndex(messelectedA-1); 
            jComboBox7Mes.setSelectedIndex(messelectedA-1);  
            jComboBox8Mes.setSelectedIndex(messelectedA-1);
            DoConnectB();
        }
    }//GEN-LAST:event_jComboBox9MesActionPerformed

    private void jComboBoxProduto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto9ActionPerformed
       if (jCheckBox1.isSelected() && iJ!=0) {
            messelectedA = jComboBox9Mes.getSelectedIndex()+1;
            produtoselectedA = jComboBoxProduto9.getSelectedIndex()+1;
            jComboBoxProduto1.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto2.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto3.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto4.setSelectedIndex(produtoselectedA-1);
            jComboBoxProduto5.setSelectedIndex(produtoselectedA-1); 
            jComboBoxProduto6.setSelectedIndex(produtoselectedA-1); 
            jComboBoxProduto7.setSelectedIndex(produtoselectedA-1);  
            jComboBoxProduto8.setSelectedIndex(produtoselectedA-1);
            jComboBox1Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox2Mes.setSelectedIndex(messelectedA-1);
            jComboBox3Mes.setSelectedIndex(messelectedA-1);
            jComboBox4Mes.setSelectedIndex(messelectedA-1);
            jComboBox5Mes.setSelectedIndex(messelectedA-1); 
            jComboBox6Mes.setSelectedIndex(messelectedA-1); 
            jComboBox7Mes.setSelectedIndex(messelectedA-1);  
            jComboBox8Mes.setSelectedIndex(messelectedA-1);
            DoConnectB();
        }
       iJ++;
    }//GEN-LAST:event_jComboBoxProduto9ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextRestauranteAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteAKeyPressed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteAKeyPressed

    private void jTextRestauranteBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteBKeyPressed
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteBKeyPressed

    private void jTextRestauranteCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteCKeyPressed
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteCKeyPressed

    private void jTextRestauranteDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteDKeyPressed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteDKeyPressed

    private void jTextRestauranteEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteEKeyPressed
        jButton5.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteEKeyPressed

    private void jTextRestauranteFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteFKeyPressed
        jButton6.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteFKeyPressed

    private void jTextRestauranteGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteGKeyPressed
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteGKeyPressed

    private void jTextRestauranteHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRestauranteHKeyPressed
        jButton8.setEnabled(true);
    }//GEN-LAST:event_jTextRestauranteHKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormsPreEncomendas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jBtnPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1Mes;
    private javax.swing.JComboBox jComboBox2Mes;
    private javax.swing.JComboBox jComboBox3Mes;
    private javax.swing.JComboBox jComboBox4Mes;
    private javax.swing.JComboBox jComboBox5Mes;
    private javax.swing.JComboBox jComboBox6Mes;
    private javax.swing.JComboBox jComboBox7Mes;
    private javax.swing.JComboBox jComboBox8Mes;
    private javax.swing.JComboBox jComboBox9Mes;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JComboBox jComboBoxProduto1;
    private javax.swing.JComboBox jComboBoxProduto2;
    private javax.swing.JComboBox jComboBoxProduto3;
    private javax.swing.JComboBox jComboBoxProduto4;
    private javax.swing.JComboBox jComboBoxProduto5;
    private javax.swing.JComboBox jComboBoxProduto6;
    private javax.swing.JComboBox jComboBoxProduto7;
    private javax.swing.JComboBox jComboBoxProduto8;
    private javax.swing.JComboBox jComboBoxProduto9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JTextField jTextRestauranteA;
    private javax.swing.JTextField jTextRestauranteB;
    private javax.swing.JTextField jTextRestauranteC;
    private javax.swing.JTextField jTextRestauranteD;
    private javax.swing.JTextField jTextRestauranteE;
    private javax.swing.JTextField jTextRestauranteF;
    private javax.swing.JTextField jTextRestauranteG;
    private javax.swing.JTextField jTextRestauranteH;
    // End of variables declaration//GEN-END:variables

    private void closeApplication() {
        dispose();
    }

    private void DoConnect() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/" + dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            /*String sql = "SELECT * FROM produtos WHERE jan="+jan+" OR fev="+fev+" OR mar="+mar+" OR abr="+abr+" OR mai="+mai+" OR"
                    + " jun="+jun+" OR jul="+jul+" OR ago="+ago+" OR sete="+set+" OR outu="+out+" OR nov="+nov+" OR dez="+dez;
                    * 
                    */
            String sql = "SELECT * FROM produtos";
            rs = stmt.executeQuery(sql);
            rs.next();
             
           //Listagem dos Produtos
            
            rs.beforeFirst();
             if (variavelControlNomeProdutos==false) {
                while (rs.next()){  
                    jComboBoxProduto1.addItem(rs.getString("Nome"));
                    jComboBoxProduto2.addItem(rs.getString("Nome"));
                    jComboBoxProduto3.addItem(rs.getString("Nome"));
                    jComboBoxProduto4.addItem(rs.getString("Nome"));
                    jComboBoxProduto5.addItem(rs.getString("Nome")); 
                    jComboBoxProduto6.addItem(rs.getString("Nome"));  
                    jComboBoxProduto7.addItem(rs.getString("Nome"));  
                    jComboBoxProduto8.addItem(rs.getString("Nome")); 
                    jComboBoxProduto9.addItem(rs.getString("Nome")); 

                }   
                variavelControlNomeProdutos=true;
            }
             else {
                 jComboBoxProduto1.setSelectedIndex(0);
                 jComboBoxProduto2.setSelectedIndex(0);
                 jComboBoxProduto3.setSelectedIndex(0);
                 jComboBoxProduto4.setSelectedIndex(0);;
                 jComboBoxProduto5.setSelectedIndex(0); 
                 jComboBoxProduto6.setSelectedIndex(0); 
                 jComboBoxProduto7.setSelectedIndex(0);  
                 jComboBoxProduto8.setSelectedIndex(0);
                 jComboBoxProduto9.setSelectedIndex(0);
             }
             rs.close();
            //Restaurante A
            stmt2 = con.createStatement();
           
            String sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=1 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            ResultSet rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteA.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Restaurante B
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=2 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteB.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Restaurante C
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=3 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteC.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Restaurante D
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=4 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana D
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteD.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Restaurante E
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=5 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana E
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteE.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
            
             //Restaurante F
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=6 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana F
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteF.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
            //Restaurante G
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=7 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana G
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextRestauranteG.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
            //Restaurante H
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".pre_encomenda "
                    + "WHERE mes="+getMonth +" AND ano=" + ano+" AND restaurantes_idrestaurantes=8 "
                    + "AND produtos_idprodutos="+produtoselectedA;
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana H
            
            rs2.beforeFirst();
            rs.close();
            while (rs2.next()){  
                jTextRestauranteH.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsPreEncomendas.this, err.getMessage());
        }
    }

    private void DoConnectA() {
        try{
            
            //Restaurante A
            if (restauranteSelected == 1) {
               jTextRestauranteA.setText("");
           }
            if (restauranteSelected == 2) {
                jTextRestauranteB.setText("");
            }
            if (restauranteSelected == 3) {
                jTextRestauranteC.setText("");
            }
            if (restauranteSelected == 4) {
                jTextRestauranteD.setText("");
            }
            if (restauranteSelected == 5) {
                jTextRestauranteE.setText("");
            }
            if (restauranteSelected == 6) {
                jTextRestauranteF.setText("");
            }
            if (restauranteSelected == 7) {
                jTextRestauranteG.setText("");
            }
            if (restauranteSelected == 8) {
                jTextRestauranteH.setText("");
            }
            
            String sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=" + restauranteSelected
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            ResultSet rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
            while (rs2.next()){  
                if (restauranteSelected == 1) {
                    jTextRestauranteA.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 2) {
                    jTextRestauranteB.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 3) {
                    jTextRestauranteC.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 4) {
                    jTextRestauranteD.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 5) {
                    jTextRestauranteE.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 6) {
                    jTextRestauranteF.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 7) {
                    jTextRestauranteG.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (restauranteSelected == 8) {
                    jTextRestauranteH.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
            }   
             
            rs2.close();
           
             }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsPreEncomendas.this, err.getMessage());
        }
    }

    private void DoConnectB() {
        try{
            
            
            jTextRestauranteA.setText("");
            jTextRestauranteB.setText("");
            jTextRestauranteC.setText("");
            jTextRestauranteD.setText("");
            jTextRestauranteE.setText("");
            jTextRestauranteF.setText("");
            jTextRestauranteG.setText("");
            jTextRestauranteH.setText("");
           
            
            String sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=1"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            ResultSet rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteA.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Restaurante B
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=2"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteB.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //RestauranteC
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=3"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteC.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Restaurante D
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=4"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteD.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Restaurante E
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=5"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteE.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Restaurante 6
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=6"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteF.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Restaurante G
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=7"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteG.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Restaurante H
            sql1 = "SELECT SUM(quantidade) FROM "
                    + "" + dbName + ".pre_encomenda WHERE mes="+ messelectedA
                    + " AND ano ="+ano+"  AND restaurantes_idrestaurantes=8"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextRestauranteH.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
             }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsPreEncomendas.this, err.getMessage());
        }
    }
}
