/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class FormsArmazenagem extends javax.swing.JFrame {

    /**
     * Creates new form FormsArmazenagem
     */
    static String dbName = "daquinta_teste"; //Nome do Banco criado
    
     DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
    
    java.util.Date date = new java.util.Date();
    
    Calendar cal = Calendar.getInstance();
    Calendar calUk = Calendar.getInstance(Locale.UK);  
    
    Calendar Datam;  
    Integer getMonth = 1;
    Integer ano = date.getYear()+1900;
    
    Connection con, con2;
    Statement stmt, stmt2;
    ResultSet rs, rsProdutos;
    int curRow = 0;
    int IDs = 1;
    DB conDB = new DB();
    boolean editar = false, criarnovo=false, variavelControlNomeProdutos=false;
    
    int produtor;
    
    int iA=0, iB=0, iC=0, iD=0, iE=0, iF=0, iG=0, iH=0;
    int mA=0, mB=0, mC=0, mD=0, mE=0, mF=0, mG=0, mH=0;
    int iJ=0;
    Integer produtorSelected;
    
    String produtoselectedA, produtoselectedB, produtoselectedC, produtoselectedD, produtoselectedE, produtoselectedF, produtoselectedG, produtoselectedH;
    Integer messelectedA, messelectedB, messelectedC, messelectedD, messelectedE, messelectedF, messelectedG, messelectedH;
   
    int idProduto;
       
    public FormsArmazenagem() {
        initComponents();
        
        produtoselectedA = (String) jComboBoxProduto1.getSelectedItem(); 
        jComboBoxAno.setSelectedIndex(ano-2011);
        
        DoConnect();
        setLocationRelativeTo(null);
        
        jLabelData.setText(dateFormat.format(date).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxAno = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jBtnPesquisa = new javax.swing.JButton();
        jTextProdutorD = new javax.swing.JTextField();
        jComboBoxProduto5 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextProdutorE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox9Mes = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox4Mes = new javax.swing.JComboBox();
        jComboBox5Mes = new javax.swing.JComboBox();
        jComboBox3Mes = new javax.swing.JComboBox();
        jComboBoxProduto2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextProdutorC = new javax.swing.JTextField();
        jComboBoxProduto3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBoxProduto4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextProdutorB = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1Mes = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2Mes = new javax.swing.JComboBox();
        jComboBoxProduto1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextProdutorA = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Armazenagem");
        setResizable(false);

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015" }));

        jLabel11.setText("kg");

        jBtnPesquisa.setText("Pesquisa");
        jBtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaActionPerformed(evt);
            }
        });

        jTextProdutorD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorD.setText("0");
        jTextProdutorD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorDKeyPressed(evt);
            }
        });

        jComboBoxProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Jardim da Boa Palavra");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextProdutorE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorE.setText("0");
        jTextProdutorE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorEKeyPressed(evt);
            }
        });

        jLabel13.setText("kg");

        jComboBox9Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox9Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9MesActionPerformed(evt);
            }
        });

        jLabel16.setText("Definir para todos");

        jCheckBox1.setSelected(true);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jComboBox4Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox4Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4MesActionPerformed(evt);
            }
        });

        jComboBox5Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox5Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5MesActionPerformed(evt);
            }
        });

        jComboBox3Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox3Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3MesActionPerformed(evt);
            }
        });

        jComboBoxProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Luis Godinho");

        jLabel7.setText("Ricardo Matos");

        jTextProdutorC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorC.setText("0");
        jTextProdutorC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorCKeyPressed(evt);
            }
        });

        jComboBoxProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto3ActionPerformed(evt);
            }
        });

        jLabel9.setText("kg");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBoxProduto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Quinta da Várzes");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Quantidade");

        jLabel5.setText("kg");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Produtor");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Produto");

        jLabel6.setText("kg");

        jTextProdutorB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorB.setText("0");
        jTextProdutorB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorBKeyPressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setText("DATA:");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/10.png"))); // NOI18N
        jButton11.setText("Listagem");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setMaximumSize(new java.awt.Dimension(111, 41));
        btnCancel.setMinimumSize(new java.awt.Dimension(111, 41));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabelData.setText("88-88.8888");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/35.png"))); // NOI18N
        jLabel14.setText("Produtos Armazenáveis");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jComboBox1Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox1Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1MesActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setText("Mês");

        jComboBox2Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox2Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2MesActionPerformed(evt);
            }
        });

        jComboBoxProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Special Flowers");

        jTextProdutorA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorA.setText("0");
        jTextProdutorA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorAKeyPressed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jBtnPesquisa))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBox1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox9Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12))
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox5Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox4Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2Mes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxProduto4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProduto3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProduto2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProduto1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextProdutorD)
                            .addComponent(jTextProdutorA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextProdutorB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextProdutorC)
                            .addComponent(jTextProdutorE, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelData)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox9Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(jTextProdutorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton4)
                    .addComponent(jLabel6)
                    .addComponent(jTextProdutorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton5)
                    .addComponent(jLabel9)
                    .addComponent(jTextProdutorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton7)
                    .addComponent(jLabel11)
                    .addComponent(jTextProdutorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton9)
                    .addComponent(jLabel13)
                    .addComponent(jTextProdutorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPesquisa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaActionPerformed
        // TODO add your handling code here:
        ano = Integer.parseInt((String) jComboBoxAno.getSelectedItem());
        messelectedA = 1;
        produtoselectedA = jComboBox1.getName();
        jComboBoxProduto1.setSelectedIndex(0);
        jComboBoxProduto2.setSelectedIndex(0);
        jComboBoxProduto3.setSelectedIndex(0);
        jComboBoxProduto4.setSelectedIndex(0);
        jComboBoxProduto5.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        jComboBox1Mes.setSelectedIndex(0);
        jComboBox2Mes.setSelectedIndex(0);
        jComboBox3Mes.setSelectedIndex(0);
        jComboBox4Mes.setSelectedIndex(0);
        jComboBox5Mes.setSelectedIndex(0);
        jComboBox9Mes.setSelectedIndex(0);
        DoConnect();
    }//GEN-LAST:event_jBtnPesquisaActionPerformed

    private void jComboBoxProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto5ActionPerformed
        messelectedA = jComboBox5Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto5.getSelectedItem(); 
        produtorSelected = 5;
        if (iE > 0) {
            DoConnectA();
        }
        iE++;
    }//GEN-LAST:event_jComboBoxProduto5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        produtor = 4;
        
        jButton7.setEnabled(false);

        String produto = (String) jComboBoxProduto4.getSelectedItem();

        int quantidade = Integer.parseInt(jTextProdutorD.getText());

        String mes = (String) jComboBox4Mes.getSelectedItem();
        int m = 0;

        if (mes.equals("Janeiro")) {
            m = 1;
        }
        if (mes.equals("Fevereiro")) {
            m = 2;
        }
        if (mes.equals("Março")) {
            m = 3;
        }
        if (mes.equals("Abril")) {
            m = 4;
        }
        if (mes.equals("Maio")) {
            m = 5;
        }
        if (mes.equals("Junho")) {
            m = 6;
        }
        if (mes.equals("Julho")) {
            m = 7;
        }
        if (mes.equals("Agosto")) {
            m = 8;
        }
        if (mes.equals("Setembro")) {
            m = 9;
        }
        if (mes.equals("Outubro")) {
            m = 10;
        }
        if (mes.equals("Novembro")) {
            m = 11;
        }
        if (mes.equals("Dezembro")) {
            m = 12;
        }

        if (quantidade >= 0) {
            conDB.AdicionarStockArmazenaveis(produtor, produto, quantidade, m);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsArmazenagem.this, "Quantidade tem que ser superior a 0(zero)");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        produtor = 5;

        jButton9.setEnabled(false);
        
        String produto = (String) jComboBoxProduto5.getSelectedItem();

        int quantidade = Integer.parseInt(jTextProdutorE.getText());

        String mes = (String) jComboBox5Mes.getSelectedItem();
        int m = 0;

        if (mes.equals("Janeiro")) {
            m = 1;
        }
        if (mes.equals("Fevereiro")) {
            m = 2;
        }
        if (mes.equals("Março")) {
            m = 3;
        }
        if (mes.equals("Abril")) {
            m = 4;
        }
        if (mes.equals("Maio")) {
            m = 5;
        }
        if (mes.equals("Junho")) {
            m = 6;
        }
        if (mes.equals("Julho")) {
            m = 7;
        }
        if (mes.equals("Agosto")) {
            m = 8;
        }
        if (mes.equals("Setembro")) {
            m = 9;
        }
        if (mes.equals("Outubro")) {
            m = 10;
        }
        if (mes.equals("Novembro")) {
            m = 11;
        }
        if (mes.equals("Dezembro")) {
            m = 12;
        }

        if (quantidade >= 0) {
            conDB.AdicionarStockArmazenaveis(produtor, produto, quantidade, m);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsArmazenagem.this, "Quantidade tem que ser superior a 0(zero)");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox9MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9MesActionPerformed
        if (jCheckBox1.isSelected()) {
            
            messelectedA = jComboBox9Mes.getSelectedIndex() + 1;
            
            produtoselectedA = (String) jComboBox1.getSelectedItem(); 
            
            jComboBoxProduto1.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto2.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto3.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto4.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto5.setSelectedItem((String) jComboBox1.getSelectedItem());
            
            jComboBox1Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox2Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox3Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox4Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox5Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            DoConnectB();
        }
    }//GEN-LAST:event_jComboBox9MesActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

   }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox4MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4MesActionPerformed
        messelectedA = jComboBox4Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto4.getSelectedItem();
        produtorSelected = 4;
        if (mD > 0) {
            DoConnectA();
        }
        mD++;
    }//GEN-LAST:event_jComboBox4MesActionPerformed

    private void jComboBox5MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5MesActionPerformed
        messelectedA = jComboBox5Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto5.getSelectedItem();
        produtorSelected = 5;
        if (mE > 0) {
            DoConnectA();
        }
        mE++;
    }//GEN-LAST:event_jComboBox5MesActionPerformed

    private void jComboBox3MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3MesActionPerformed
        messelectedA = jComboBox3Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto3.getSelectedItem();
        produtorSelected = 3;
        if (mC > 0) {
            DoConnectA();
        }
        mC++;
    }//GEN-LAST:event_jComboBox3MesActionPerformed

    private void jComboBoxProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto2ActionPerformed
        messelectedA = jComboBox2Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto2.getSelectedItem();
        produtorSelected = 2;
        if (iB > 0) {
            DoConnectA();
        }
        iB++;
    }//GEN-LAST:event_jComboBoxProduto2ActionPerformed

    private void jComboBoxProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto3ActionPerformed
        messelectedA = jComboBox3Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto3.getSelectedItem();
        produtorSelected = 3;
        if (iC > 0) {
            DoConnectA();
        }
        iC++;
    }//GEN-LAST:event_jComboBoxProduto3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        produtor = 3;

        jButton5.setEnabled(false);
        
        String produto = (String) jComboBoxProduto3.getSelectedItem();

        int quantidade = Integer.parseInt(jTextProdutorC.getText());

        String mes = (String) jComboBox3Mes.getSelectedItem();
        int m = 0;

        if (mes.equals("Janeiro")) {
            m = 1;
        }
        if (mes.equals("Fevereiro")) {
            m = 2;
        }
        if (mes.equals("Março")) {
            m = 3;
        }
        if (mes.equals("Abril")) {
            m = 4;
        }
        if (mes.equals("Maio")) {
            m = 5;
        }
        if (mes.equals("Junho")) {
            m = 6;
        }
        if (mes.equals("Julho")) {
            m = 7;
        }
        if (mes.equals("Agosto")) {
            m = 8;
        }
        if (mes.equals("Setembro")) {
            m = 9;
        }
        if (mes.equals("Outubro")) {
            m = 10;
        }
        if (mes.equals("Novembro")) {
            m = 11;
        }
        if (mes.equals("Dezembro")) {
            m = 12;
        }

        if (quantidade >= 0) {
            conDB.AdicionarStockArmazenaveis(produtor, produto, quantidade, m);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsArmazenagem.this, "Quantidade tem que ser superior a 0(zero)");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxProduto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto4ActionPerformed
        messelectedA = jComboBox4Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto4.getSelectedItem();
        produtorSelected = 4;
        if (iD > 0) {
            DoConnectA();
        }
        iD++;
    }//GEN-LAST:event_jComboBoxProduto4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        produtor = 2;

        jButton4.setEnabled(false);
        
        String produto = (String) jComboBoxProduto2.getSelectedItem();

        int quantidade = Integer.parseInt(jTextProdutorB.getText());

        String mes = (String) jComboBox2Mes.getSelectedItem();
        int m = 0;

        if (mes.equals("Janeiro")) {
            m = 1;
        }
        if (mes.equals("Fevereiro")) {
            m = 2;
        }
        if (mes.equals("Março")) {
            m = 3;
        }
        if (mes.equals("Abril")) {
            m = 4;
        }
        if (mes.equals("Maio")) {
            m = 5;
        }
        if (mes.equals("Junho")) {
            m = 6;
        }
        if (mes.equals("Julho")) {
            m = 7;
        }
        if (mes.equals("Agosto")) {
            m = 8;
        }
        if (mes.equals("Setembro")) {
            m = 9;
        }
        if (mes.equals("Outubro")) {
            m = 10;
        }
        if (mes.equals("Novembro")) {
            m = 11;
        }
        if (mes.equals("Dezembro")) {
            m = 12;
        }

        if (quantidade >= 0) {
            conDB.AdicionarStockArmazenaveis(produtor, produto, quantidade, m);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsArmazenagem.this, "Quantidade tem que ser superior a 0(zero)");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        produtor = 1;
        
        jButton1.setEnabled(false);
        
        String produto = (String) jComboBoxProduto1.getSelectedItem();
        
        int quantidade = Integer.parseInt(jTextProdutorA.getText());

        String mes = (String) jComboBox1Mes.getSelectedItem();
        int m = 0;

        if (mes.equals("Janeiro")) {
            m = 1;
        }
        if (mes.equals("Fevereiro")) {
            m = 2;
        }
        if (mes.equals("Março")) {
            m = 3;
        }
        if (mes.equals("Abril")) {
            m = 4;
        }
        if (mes.equals("Maio")) {
            m = 5;
        }
        if (mes.equals("Junho")) {
            m = 6;
        }
        if (mes.equals("Julho")) {
            m = 7;
        }
        if (mes.equals("Agosto")) {
            m = 8;
        }
        if (mes.equals("Setembro")) {
            m = 9;
        }
        if (mes.equals("Outubro")) {
            m = 10;
        }
        if (mes.equals("Novembro")) {
            m = 11;
        }
        if (mes.equals("Dezembro")) {
            m = 12;
        }

        if (quantidade >= 0) {
            conDB.AdicionarStockArmazenaveis(produtor, produto, quantidade, m);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsArmazenagem.this, "Quantidade tem que ser superior a 0(zero)");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        ListaArmazenaveis preEnco = new ListaArmazenaveis();
        preEnco.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:

        closeApplication();


    }//GEN-LAST:event_btnCancelActionPerformed

    private void jComboBox1MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1MesActionPerformed
        messelectedA = jComboBox1Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto1.getSelectedItem();
        produtorSelected = 1;
        if (mA > 0) {
            DoConnectA();
        }
        mA++;
    }//GEN-LAST:event_jComboBox1MesActionPerformed

    private void jComboBox2MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2MesActionPerformed
        messelectedA = jComboBox2Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto2.getSelectedItem();
        produtorSelected = 2;
        if (mB > 0) {
            DoConnectA();
        }
        mB++;
    }//GEN-LAST:event_jComboBox2MesActionPerformed

    private void jComboBoxProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto1ActionPerformed
        messelectedA = jComboBox1Mes.getSelectedIndex() + 1;
        produtoselectedA = (String) jComboBoxProduto1.getSelectedItem();
        produtorSelected = 1;
        if (iA > 0) {
            DoConnectA();
        }
        iA++;
    }//GEN-LAST:event_jComboBoxProduto1ActionPerformed

    private void jTextProdutorAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorAKeyPressed
       jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorAKeyPressed

    private void jTextProdutorBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorBKeyPressed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorBKeyPressed

    private void jTextProdutorCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorCKeyPressed
        jButton5.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorCKeyPressed

    private void jTextProdutorDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorDKeyPressed
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorDKeyPressed

    private void jTextProdutorEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorEKeyPressed
        jButton9.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorEKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if (jCheckBox1.isSelected() && iJ != 0) {
            messelectedA = jComboBox9Mes.getSelectedIndex() + 1;
            produtoselectedA = (String) jComboBox1.getSelectedItem(); 
            
             
            
            jComboBoxProduto1.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto2.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto3.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto4.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBoxProduto5.setSelectedItem((String) jComboBox1.getSelectedItem());
            jComboBox1Mes.setSelectedItem(jComboBox9Mes.getSelectedItem());
            jComboBox2Mes.setSelectedIndex(messelectedA - 1);
            jComboBox3Mes.setSelectedIndex(messelectedA - 1);
            jComboBox4Mes.setSelectedIndex(messelectedA - 1);
            jComboBox5Mes.setSelectedIndex(messelectedA - 1);
            DoConnectB();
        }
        iJ++;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsArmazenagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsArmazenagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsArmazenagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsArmazenagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormsArmazenagem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jBtnPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox1Mes;
    private javax.swing.JComboBox jComboBox2Mes;
    private javax.swing.JComboBox jComboBox3Mes;
    private javax.swing.JComboBox jComboBox4Mes;
    private javax.swing.JComboBox jComboBox5Mes;
    private javax.swing.JComboBox jComboBox9Mes;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JComboBox jComboBoxProduto1;
    private javax.swing.JComboBox jComboBoxProduto2;
    private javax.swing.JComboBox jComboBoxProduto3;
    private javax.swing.JComboBox jComboBoxProduto4;
    private javax.swing.JComboBox jComboBoxProduto5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JTextField jTextProdutorA;
    private javax.swing.JTextField jTextProdutorB;
    private javax.swing.JTextField jTextProdutorC;
    private javax.swing.JTextField jTextProdutorD;
    private javax.swing.JTextField jTextProdutorE;
    // End of variables declaration//GEN-END:variables

    private void DoConnect() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/"+ dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM produtos WHERE tipo=2";
            rs = stmt.executeQuery(sql);
            rs.next();
             
           //Listagem dos Produtos
            
            rs.beforeFirst();
             if (variavelControlNomeProdutos==false) {
                while (rs.next()){  
                    jComboBoxProduto1.addItem(rs.getString("Nome"));
                    jComboBoxProduto2.addItem(rs.getString("Nome"));
                    jComboBoxProduto3.addItem(rs.getString("Nome"));
                    jComboBoxProduto4.addItem(rs.getString("Nome"));
                    jComboBoxProduto5.addItem(rs.getString("Nome"));
                    jComboBox1.addItem(rs.getString("Nome")); 

                }   
                variavelControlNomeProdutos=true;
            }
             else {
                 jComboBoxProduto1.setSelectedIndex(0);
                 jComboBoxProduto2.setSelectedIndex(0);
                 jComboBoxProduto3.setSelectedIndex(0);
                 jComboBoxProduto4.setSelectedIndex(0);
                 jComboBoxProduto5.setSelectedIndex(0);
                 jComboBox1.setSelectedIndex(0);
             }
             rs.close();
            //Produtor A
            stmt2 = con.createStatement();
           
            String sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+getMonth +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=1 AND produtos.nome='"+produtoselectedA+"'";
            
              
            
            ResultSet rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextProdutorA.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Produtor B
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+getMonth +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=2 AND produtos.nome='"+produtoselectedA+"'";
            
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextProdutorB.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Produtor C
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+getMonth +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=3 AND produtos.nome='"+produtoselectedA+"'";
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextProdutorC.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Produtor D
            stmt2 = con.createStatement();
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+getMonth +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=4 AND produtos.nome='"+produtoselectedA+"'";
            
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana D
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextProdutorD.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
             //Produtor E
            stmt2 = con.createStatement();
            
            sql1 =  "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+getMonth +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=5 AND produtos.nome='"+produtoselectedA+"'";
                    
                    
                 
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
           
            //Listagem dos Produtos por semana E
            
            rs2.beforeFirst();
           
            while (rs2.next()){  
                jTextProdutorE.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));  
            }   
            
            rs2.close();
            
                                
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsArmazenagem.this, err.getMessage());
        }
    }

    private void DoConnectA() {
        try{
            
            //Produtor A
            if (produtorSelected == 1) {
               jTextProdutorA.setText("");
           }
            if (produtorSelected == 2) {
                jTextProdutorB.setText("");
            }
            if (produtorSelected == 3) {
                jTextProdutorC.setText("");
            }
            if (produtorSelected == 4) {
                jTextProdutorD.setText("");
            }
            if (produtorSelected == 5) {
                jTextProdutorE.setText("");
            }
           
            
            String sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+ messelectedA +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=" + produtorSelected+" AND produtos.nome='"+produtoselectedA+"'";
                    
                    
            
            ResultSet rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
            while (rs2.next()){  
                if (produtorSelected == 1) {
                    jTextProdutorA.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (produtorSelected == 2) {
                    jTextProdutorB.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (produtorSelected == 3) {
                    jTextProdutorC.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (produtorSelected == 4) {
                    jTextProdutorD.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
                if (produtorSelected == 5) {
                    jTextProdutorE.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
                }
             
            }   
             
            rs2.close();
             }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsArmazenagem.this, err.getMessage());
        }
    }

    private void DoConnectB() {
        try{
            
            
            jTextProdutorA.setText("");
            jTextProdutorB.setText("");
            jTextProdutorC.setText("");
            jTextProdutorD.setText("");
            jTextProdutorE.setText("");
         
           
           
            String sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+ messelectedA +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=1 AND produtos.nome='"+produtoselectedA+"'";
        
            
            ResultSet rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorA.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Produtor B
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+ messelectedA +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=2 AND produtos.nome='"+produtoselectedA+"'";
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorB.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Produtor
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+ messelectedA +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=3 AND produtos.nome='"+produtoselectedA+"'";
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorC.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Produtor D
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+ messelectedA +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=4 AND produtos.nome='"+produtoselectedA+"'";
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorD.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            //Produtor E
            sql1 = "SELECT SUM(quantidade) FROM " + dbName + ".stock "
                    + "INNER JOIN " + dbName + ".produtos "
                    + "ON " + dbName + ".produtos.idprodutos=" + dbName + ".stock.produtos_idprodutos "
                    + "WHERE stock.mes="+ messelectedA +" AND stock.ano=" + ano+" "
                    + "AND stock.produtores_idprodutores=5 AND produtos.nome='"+produtoselectedA+"'";
            
            rs2 = stmt.executeQuery(sql1);
            rs2.next();
                       
            rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorE.setText(Integer.toString(rs2.getInt("SUM(quantidade)")));   
            }   
            rs2.close();
            
             }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsArmazenagem.this, err.getMessage());
        }
    }

    private void closeApplication() {
        dispose();
    }
}
