/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Toshiba
 */
public class FormProdutores extends javax.swing.JFrame {

    /**
     * Creates new form FormProdutores
     */
    
    static String dbName = "daquinta_teste"; //Nome do Banco criado
     Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;
    int IDs = 1;
    boolean criarnovo = false, editar=false;
    
    DB conDB = new DB();
    
    
    String produtor;
    
    public FormProdutores() {
        initComponents();
        DoConnect();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIDRestaurante = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textGPSRestaurante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNomeRestaurante = new javax.swing.JTextField();
        textMoradaRestaurante = new javax.swing.JTextField();
        textTelefoneRestaurante = new javax.swing.JTextField();
        textNIFRestaurante = new javax.swing.JTextField();
        btnSaveRecord1 = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        btnUpdateRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        btnSaveRecord = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textHistoricoRestaurante = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtores");
        setAutoRequestFocus(false);
        setResizable(false);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/54.png"))); // NOI18N
        jLabel9.setText("Fornecedores | Quintas");

        jLabel6.setText("Notas");

        jLabel5.setText("Coordenadas GPS");

        jLabel7.setText("Telefone");

        jLabel1.setText("ID:");

        jLabel4.setText("NIF");

        jLabel3.setText("Morada");

        jLabel2.setText("Nome");

        btnSaveRecord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnSaveRecord1.setText("Cancelar");
        btnSaveRecord1.setMaximumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord1.setMinimumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecord1ActionPerformed(evt);
            }
        });

        btnNewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/8.png"))); // NOI18N
        btnNewRecord.setText("Novo");
        btnNewRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnNewRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnUpdateRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/2.png"))); // NOI18N
        btnUpdateRecord.setText("Editar");
        btnUpdateRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnUpdateRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/9.png"))); // NOI18N
        btnDeleteRecord.setText("Eliminar");
        btnDeleteRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnDeleteRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        btnSaveRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/7.png"))); // NOI18N
        btnSaveRecord.setText("Guardar");
        btnSaveRecord.setEnabled(false);
        btnSaveRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/94.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/98.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/99.png"))); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/92.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        textHistoricoRestaurante.setColumns(20);
        textHistoricoRestaurante.setRows(5);
        jScrollPane2.setViewportView(textHistoricoRestaurante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textGPSRestaurante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNIFRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(2, 2, 2)
                                .addComponent(textTelefoneRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textMoradaRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSaveRecord1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNewRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdateRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSaveRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textIDRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textIDRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textMoradaRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textTelefoneRestaurante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNIFRestaurante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textGPSRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFirst)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext)
                            .addComponent(btnLast)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecord1ActionPerformed
        // TODO add your handling code here:
        if (criarnovo == true) { //Is new
            criarnovo = false;
            btnFirst.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(true);
            btnLast.setEnabled(true);
            btnUpdateRecord.setEnabled(true);
            btnDeleteRecord.setEnabled(true);
            btnNewRecord.setEnabled(true);

            btnSaveRecord.setEnabled(true);
        } else if (editar == true) {
            
            editar = false;
            btnFirst.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(true);
            btnLast.setEnabled(true);
            btnUpdateRecord.setEnabled(true);
            btnDeleteRecord.setEnabled(true);
            btnNewRecord.setEnabled(true);
        } else {
            closeApplication();
        }



    }//GEN-LAST:event_btnSaveRecord1ActionPerformed

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
        // TODO add your handling code here:
        try {
            btnSaveRecord.setEnabled(true);
            criarnovo = true;
            editar = false;
            textIDRestaurante.setEnabled(true);
            textNomeRestaurante.setEnabled(true);
            textMoradaRestaurante.setEnabled(true);
            textTelefoneRestaurante.setEnabled(true);   
            textNIFRestaurante.setEnabled(true);
            textGPSRestaurante.setEnabled(true);
            textHistoricoRestaurante.setEnabled(true);
            
            rs.last();
            int id_col = rs.getInt("idfornecedores");
            //curRow = rs.getRow();
            textIDRestaurante.setEnabled(false);
            textIDRestaurante.setText(Integer.toString(id_col+1));
            textNomeRestaurante.setText(" ");
            textMoradaRestaurante.setText(" ");
            textTelefoneRestaurante.setText("1");     
            textNIFRestaurante.setText("1"); 
            textGPSRestaurante.setText(" ");
            textHistoricoRestaurante.setText(" ");
            
            btnFirst.setEnabled( false );
            btnPrevious.setEnabled( false ) ;
            btnNext.setEnabled( false );
            btnLast.setEnabled( false );
            btnUpdateRecord.setEnabled( false );
            btnDeleteRecord.setEnabled( false );
            btnNewRecord.setEnabled( false );

            btnSaveRecord.setEnabled( true );

        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        // TODO add your handling code here:
        try {
            btnSaveRecord.setEnabled(true);
            editar = true;
            textIDRestaurante.setEnabled(false);
            textNomeRestaurante.setEnabled(true);
            textMoradaRestaurante.setEnabled(true);
            textTelefoneRestaurante.setEnabled(true);
            textNIFRestaurante.setEnabled(true);
            textGPSRestaurante.setEnabled(true);
            textHistoricoRestaurante.setEnabled(true);
            int id_col = rs.getInt("idfornecedores");
            //curRow = rs.getRow();

        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed
        // TODO add your handling code here:
        try {

            curRow = rs.getRow();
            rs.absolute(curRow);

            int ID = Integer.valueOf(textIDRestaurante.getText());
            String Name = textNomeRestaurante.getText();
            String Morada = textMoradaRestaurante.getText();
            int Telefone = Integer.valueOf(textTelefoneRestaurante.getText());
            int NIF = Integer.valueOf(textNIFRestaurante.getText());
            String GPS = textGPSRestaurante.getText();
            String Historico = textHistoricoRestaurante.getText();

            if (criarnovo == true) { //Is new
                criarnovo = false;
                conDB.inserirFornecedorNovo(Name, Morada, Telefone, NIF, GPS, Historico);
            } else if (editar == true) {
                editar = false;
                conDB.inserirFornecedorEditar(ID, Name, Morada, Telefone, NIF, GPS, Historico);
            }




            btnFirst.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(true);
            btnLast.setEnabled(true);
            btnUpdateRecord.setEnabled(true);
            btnDeleteRecord.setEnabled(true);
            btnNewRecord.setEnabled(true);
            btnSaveRecord.setEnabled(false);
            btnSaveRecord.setEnabled(true);

            JOptionPane.showMessageDialog(FormProdutores.this, "Guardado");
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnSaveRecordActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        btnLast.setEnabled(false);
        btnNext.setEnabled(false);
        btnPrevious.setEnabled(true);
        btnFirst.setEnabled(true);
        try {

            rs.last();
            int id_col = rs.getInt("idfornecedores");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");

            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));
            textNIFRestaurante.setText(Integer.toString(NIF));
            textGPSRestaurante.setText(GPS);
            textHistoricoRestaurante.setText(Historico);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(FormProdutores.this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        try {
            if (rs.next()) {
                btnLast.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(true);
                btnFirst.setEnabled(true);
                int id_col = rs.getInt("idfornecedores");
                String Name = rs.getString("nome");
                String Morada = rs.getString("morada");
                int Telefone = rs.getInt("telefone");
                int NIF = rs.getInt("nif");
                String GPS = rs.getString("gps");
                String Historico = rs.getString("notas");

                textIDRestaurante.setText(Integer.toString(id_col));
                textNomeRestaurante.setText(Name);
                textMoradaRestaurante.setText(Morada);
                textTelefoneRestaurante.setText(Integer.toString(Telefone));
                textNIFRestaurante.setText(Integer.toString(NIF));
                textGPSRestaurante.setText(GPS);
                textHistoricoRestaurante.setText(Historico);
            } else {
                rs.previous();
                btnLast.setEnabled(false);
                btnNext.setEnabled(false);
                btnPrevious.setEnabled(true);
                btnFirst.setEnabled(true);
                JOptionPane.showMessageDialog(FormProdutores.this, "Não existem mais Clientes");
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(FormProdutores.this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.previous()) {
                btnLast.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(true);
                btnFirst.setEnabled(true);
                int id_col = rs.getInt("idfornecedores");
                String Name = rs.getString("nome");
                String Morada = rs.getString("morada");
                int Telefone = rs.getInt("telefone");
                int NIF = rs.getInt("nif");
                String GPS = rs.getString("gps");
                String Historico = rs.getString("notas");

                textIDRestaurante.setText(Integer.toString(id_col));
                textNomeRestaurante.setText(Name);
                textMoradaRestaurante.setText(Morada);
                textTelefoneRestaurante.setText(Integer.toString(Telefone));
                textNIFRestaurante.setText(Integer.toString(NIF));
                textGPSRestaurante.setText(GPS);
                textHistoricoRestaurante.setText(Historico);
            } else {
                rs.next();
                btnLast.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(false);
                btnFirst.setEnabled(false);
                JOptionPane.showMessageDialog(FormProdutores.this, "Inicio!");
            }
        } catch (SQLException err) {

            JOptionPane.showMessageDialog(FormProdutores.this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        btnFirst.setEnabled(true);
        btnNext.setEnabled(true);
        btnPrevious.setEnabled(false);
        btnFirst.setEnabled(false);
        try {
            rs.first();
            int id_col = rs.getInt("idfornecedores");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");

            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));
            textNIFRestaurante.setText(Integer.toString(NIF));
            textGPSRestaurante.setText(GPS);
            textHistoricoRestaurante.setText(Historico);


        } catch (SQLException err) {
            JOptionPane.showMessageDialog(FormProdutores.this, err.getMessage());
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProdutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProdutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProdutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProdutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormProdutores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JButton btnSaveRecord1;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textGPSRestaurante;
    private javax.swing.JTextArea textHistoricoRestaurante;
    private javax.swing.JTextField textIDRestaurante;
    private javax.swing.JTextField textMoradaRestaurante;
    private javax.swing.JTextField textNIFRestaurante;
    private javax.swing.JTextField textNomeRestaurante;
    private javax.swing.JTextField textTelefoneRestaurante;
    // End of variables declaration//GEN-END:variables

    private void DoConnect() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/" + dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM produtores";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            int id_col = rs.getInt("idfornecedores");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");
            
            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));     
            textNIFRestaurante.setText(Integer.toString(NIF)); 
            textGPSRestaurante.setText(GPS); 
            textHistoricoRestaurante.setText(Historico); 
        }
        catch (SQLException err) {
            JOptionPane.showConfirmDialog(FormProdutores.this, err.getMessage());
        }
    }

    private void closeApplication() {
        dispose();
    }

    void setUser(String jtext1) {
       produtor = jtext1;
       
       DoConnect2();
     }

    private void DoConnect2() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/" + dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM produtores WHERE nome='"+produtor+"'";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            int id_col = rs.getInt("idfornecedores");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");
            
            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));     
            textNIFRestaurante.setText(Integer.toString(NIF)); 
            textGPSRestaurante.setText(GPS); 
            textHistoricoRestaurante.setText(Historico); 
        }
        catch (SQLException err) {
            JOptionPane.showConfirmDialog(FormProdutores.this, err.getMessage());
        }
    }
}
