/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class FormsProducaoSemanal extends javax.swing.JFrame {

    /**
     * Creates new form FormsProducaoSemanal
     */
    static String dbName = "daquinta_teste"; //Nome do Banco criado
    
   DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
    
    java.util.Date date = new java.util.Date();
    
    Calendar cal = Calendar.getInstance();
     Calendar calUk = Calendar.getInstance(Locale.UK);  
    
   Calendar Datam;  
     
    Integer ano = date.getYear()+1900;
    
    
     JComboBox cbIdDisciplina, cbDisciplina; 
    
    Connection con, con2;
    Statement stmt, stmt2;
    ResultSet rs, rsProdutos;
    int curRow = 0;
    int IDs = 1;
    DB conDB = new DB();
    boolean editar = false, criarnovo=false, variavelControlNomeProdutos=false;
      int iA=0, iB=0, iC=0, iD=0, iE=0, iF=0, iG=0, iH=0, iJ=0;
    Integer getWeekofYear = calUk.get( Calendar.WEEK_OF_YEAR );
    Integer produtorSelected;
    
    Integer produtoselectedA, produtoselectedB, produtoselectedC, produtoselectedD, produtoselectedE, produtoselectedF, produtoselectedG, produtoselectedH;
   

    public FormsProducaoSemanal() {
        initComponents();
       
        if (getWeekofYear==1) jComboBoxWeek.setSelectedIndex(1);
        else jComboBoxWeek.setSelectedIndex(getWeekofYear-1);
        jComboBoxAno.setSelectedIndex(ano-2011);
        
        
        produtoselectedA = jComboBoxProduto1.getSelectedIndex()+2;
       
         setLocationRelativeTo(null);
       
        DoConnect();
        jLabelSemana.setText(getWeekofYear.toString());
        jLabelData.setText(dateFormat.format(date).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextProdutorCQui = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxProduto3 = new javax.swing.JComboBox();
        jTextProdutorCSeg = new javax.swing.JTextField();
        jTextProdutorCTer = new javax.swing.JTextField();
        jTextProdutorCQua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextProdutorBQui = new javax.swing.JTextField();
        jTextProdutorBQua = new javax.swing.JTextField();
        jTextProdutorBTer = new javax.swing.JTextField();
        jTextProdutorBSeg = new javax.swing.JTextField();
        jLabelSemana = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxProduto2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextProdutorBSex = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jTextProdutorASeg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextProdutorASex = new javax.swing.JTextField();
        jTextProdutorAQui = new javax.swing.JTextField();
        jTextProdutorAQua = new javax.swing.JTextField();
        jTextProdutorATer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancel1 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jComboBoxProduto1 = new javax.swing.JComboBox();
        jComboBoxAno = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxWeek = new javax.swing.JComboBox();
        jBtnPesquisa = new javax.swing.JButton();
        jTextProdutorETer = new javax.swing.JTextField();
        jTextProdutorEQua = new javax.swing.JTextField();
        jComboBoxProduto5 = new javax.swing.JComboBox();
        jTextProdutorESeg = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBoxProduto9 = new javax.swing.JComboBox();
        jTextProdutorESex = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jTextProdutorDSex = new javax.swing.JTextField();
        jComboBoxProduto4 = new javax.swing.JComboBox();
        jTextProdutorDSeg = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextProdutorEQui = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jTextProdutorCSex = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextProdutorDQui = new javax.swing.JTextField();
        jTextProdutorDQua = new javax.swing.JTextField();
        jTextProdutorDTer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produção Semanal");
        setPreferredSize(new java.awt.Dimension(855, 550));
        setResizable(false);

        jLabel18.setText("Qua");

        jLabel19.setText("Qui");

        jLabel14.setText("Seg");

        jLabel17.setText("Ter");

        jTextProdutorCQui.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorCQui.setText("0");
        jTextProdutorCQui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorCQui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorCQuiKeyPressed(evt);
            }
        });

        jLabel20.setText("Sex");

        jLabel21.setText("Luís Godinho");

        jComboBoxProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto3ActionPerformed(evt);
            }
        });

        jTextProdutorCSeg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorCSeg.setText("0");
        jTextProdutorCSeg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorCSeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorCSegKeyPressed(evt);
            }
        });

        jTextProdutorCTer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorCTer.setText("0");
        jTextProdutorCTer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorCTer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorCTerKeyPressed(evt);
            }
        });

        jTextProdutorCQua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorCQua.setText("0");
        jTextProdutorCQua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorCQua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorCQuaKeyPressed(evt);
            }
        });

        jLabel1.setText("Special Flowers");

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/36.png"))); // NOI18N
        jLabel56.setText("Produção");
        jLabel56.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton19.setEnabled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ricardo Matos");

        jTextProdutorBQui.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorBQui.setText("0");
        jTextProdutorBQui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorBQui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorBQuiKeyPressed(evt);
            }
        });

        jTextProdutorBQua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorBQua.setText("0");
        jTextProdutorBQua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorBQua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorBQuaKeyPressed(evt);
            }
        });

        jTextProdutorBTer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorBTer.setText("0");
        jTextProdutorBTer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorBTer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorBTerKeyPressed(evt);
            }
        });

        jTextProdutorBSeg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorBSeg.setText("0");
        jTextProdutorBSeg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorBSeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorBSegKeyPressed(evt);
            }
        });

        jLabelSemana.setText("jLabel17");

        jLabel16.setText("Semana:");

        jComboBoxProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Produto");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Produtor");

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton20.setEnabled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel15.setText("DATA:");

        jTextProdutorBSex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorBSex.setText("0");
        jTextProdutorBSex.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorBSex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorBSexKeyPressed(evt);
            }
        });

        jLabelData.setText("88-88.8888");

        jTextProdutorASeg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorASeg.setText("0");
        jTextProdutorASeg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorASeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorASegKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Quantidade");

        jLabel10.setText("Sex");

        jLabel9.setText("Qua");

        jTextProdutorASex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorASex.setText("0");
        jTextProdutorASex.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorASex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorASexKeyPressed(evt);
            }
        });

        jTextProdutorAQui.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorAQui.setText("0");
        jTextProdutorAQui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorAQui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorAQuiKeyPressed(evt);
            }
        });

        jTextProdutorAQua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorAQua.setText("0");
        jTextProdutorAQua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorAQua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorAQuaKeyPressed(evt);
            }
        });

        jTextProdutorATer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorATer.setText("0");
        jTextProdutorATer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorATer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorATerKeyPressed(evt);
            }
        });

        jLabel8.setText("Qui");

        jLabel6.setText("Seg");

        jLabel7.setText("Ter");

        btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnCancel1.setText("Cancelar");
        btnCancel1.setMaximumSize(new java.awt.Dimension(111, 41));
        btnCancel1.setMinimumSize(new java.awt.Dimension(111, 41));
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/10.png"))); // NOI18N
        jButton12.setText("Listagem");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jComboBoxProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto1ActionPerformed(evt);
            }
        });

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015" }));
        jComboBoxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoActionPerformed(evt);
            }
        });

        jLabel11.setText("Semana");

        jComboBoxWeek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55" }));
        jComboBoxWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWeekActionPerformed(evt);
            }
        });

        jBtnPesquisa.setText("Pesquisa");
        jBtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaActionPerformed(evt);
            }
        });

        jTextProdutorETer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorETer.setText("0");
        jTextProdutorETer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorETer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorETerKeyPressed(evt);
            }
        });

        jTextProdutorEQua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorEQua.setText("0");
        jTextProdutorEQua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorEQua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorEQuaKeyPressed(evt);
            }
        });

        jComboBoxProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto5ActionPerformed(evt);
            }
        });

        jTextProdutorESeg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorESeg.setText("0");
        jTextProdutorESeg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorESeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorESegKeyPressed(evt);
            }
        });

        jLabel29.setText("Definir para todos");

        jCheckBox1.setSelected(true);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jComboBoxProduto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto9ActionPerformed(evt);
            }
        });

        jTextProdutorESex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorESex.setText("0");
        jTextProdutorESex.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorESex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorESexKeyPressed(evt);
            }
        });

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton23.setEnabled(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jLabel74.setText("Seg");

        jLabel75.setText("Ter");

        jLabel76.setText("Qua");

        jLabel77.setText("Qui");

        jLabel78.setText("Sex");

        jLabel28.setText("Seg");

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton22.setEnabled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jTextProdutorDSex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorDSex.setText("0");
        jTextProdutorDSex.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorDSex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorDSexKeyPressed(evt);
            }
        });

        jComboBoxProduto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProduto4ActionPerformed(evt);
            }
        });

        jTextProdutorDSeg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorDSeg.setText("0");
        jTextProdutorDSeg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorDSeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorDSegKeyPressed(evt);
            }
        });

        jLabel73.setText("Jardim da Boa Palavra");

        jTextProdutorEQui.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorEQui.setText("0");
        jTextProdutorEQui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorEQui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorEQuiKeyPressed(evt);
            }
        });

        jLabel71.setText("Qui");

        jLabel72.setText("Sex");

        jLabel69.setText("Ter");

        jLabel70.setText("Qua");

        jLabel25.setText("Qui");

        jLabel24.setText("Qua");

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/121.png"))); // NOI18N
        jButton21.setEnabled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jTextProdutorCSex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorCSex.setText("0");
        jTextProdutorCSex.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorCSex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorCSexKeyPressed(evt);
            }
        });

        jLabel23.setText("Ter");

        jLabel22.setText("Seg");

        jLabel27.setText("Quinta da Varzea");

        jTextProdutorDQui.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorDQui.setText("0");
        jTextProdutorDQui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorDQui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorDQuiKeyPressed(evt);
            }
        });

        jTextProdutorDQua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorDQua.setText("0");
        jTextProdutorDQua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorDQua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorDQuaKeyPressed(evt);
            }
        });

        jTextProdutorDTer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextProdutorDTer.setText("0");
        jTextProdutorDTer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextProdutorDTer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextProdutorDTerKeyPressed(evt);
            }
        });

        jLabel26.setText("Sex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabelSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16)))
                .addGap(28, 28, 28)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxProduto9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel56)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextProdutorASeg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextProdutorATer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextProdutorAQua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextProdutorAQui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextProdutorASex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(57, 57, 57)
                                .addComponent(jComboBoxProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextProdutorBSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorBTer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorBQua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorBQui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorBSex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(57, 57, 57)
                                .addComponent(jComboBoxProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextProdutorCSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorCTer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorCQua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorCQui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorCSex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(57, 57, 57)
                                .addComponent(jComboBoxProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextProdutorDSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorDTer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorDQua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorDQui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorDSex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel73)
                                .addGap(57, 57, 57)
                                .addComponent(jComboBoxProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextProdutorESeg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorETer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorEQua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorEQui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextProdutorESex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisa)
                        .addGap(31, 31, 31)
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelData)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabelSemana))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(jComboBoxProduto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jTextProdutorAQui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorAQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorATer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorASeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorASex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jTextProdutorBQui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorBQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorBTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorBSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorBSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel21)
                            .addComponent(jTextProdutorCQui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorCQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorCTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorCSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorCSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel69)
                            .addComponent(jLabel28)
                            .addComponent(jLabel70)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel27)
                            .addComponent(jTextProdutorDQui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorDQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorDTer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorDSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorDSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton22))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(jLabel74)
                            .addComponent(jLabel76)
                            .addComponent(jLabel77)
                            .addComponent(jLabel78))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel73)
                            .addComponent(jTextProdutorEQui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorEQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorETer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorESeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProdutorESex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisa)
                    .addComponent(jLabel11))
                .addGap(255, 255, 255))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto3ActionPerformed
        produtoselectedA = jComboBoxProduto3.getSelectedIndex() + 1;
        produtorSelected = 3;
        if (iC > 0) {
            DoConnectA();
        }
        iC++;
    }//GEN-LAST:event_jComboBoxProduto3ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int produtor = 1;
        
        jButton19.setEnabled(false);
                
        String produto = (String) jComboBoxProduto1.getSelectedItem();

        int qtd_seg = Integer.parseInt(jTextProdutorASeg.getText());
        int qtd_ter = Integer.parseInt(jTextProdutorATer.getText());
        int qtd_qua = Integer.parseInt(jTextProdutorAQua.getText());
        int qtd_qui = Integer.parseInt(jTextProdutorAQui.getText());
        int qtd_sex = Integer.parseInt(jTextProdutorASex.getText());

        if (qtd_seg >= 0 || qtd_ter >= 0 || qtd_qua >= 0 || qtd_qui >= 0 || qtd_sex >= 0) {
            conDB.AdicionarProducaoSemanal(produtor, produto, qtd_seg, qtd_ter, qtd_qua, qtd_qui, qtd_sex, getWeekofYear, ano);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsProducaoSemanal.this, "Quantidade tem que ser superior ou igual a 0(zero) em alguma semana");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jComboBoxProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto2ActionPerformed
        produtoselectedA = jComboBoxProduto2.getSelectedIndex() + 1;
        produtorSelected = 2;
        if (iB > 0) {
            DoConnectA();
        }
        iB++;
    }//GEN-LAST:event_jComboBoxProduto2ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        int produtor = 2;
        
        jButton20.setEnabled(false);

        String produto = (String) jComboBoxProduto2.getSelectedItem();

        int qtd_seg = Integer.parseInt(jTextProdutorBSeg.getText());
        int qtd_ter = Integer.parseInt(jTextProdutorBTer.getText());
        int qtd_qua = Integer.parseInt(jTextProdutorBQua.getText());
        int qtd_qui = Integer.parseInt(jTextProdutorBQui.getText());
        int qtd_sex = Integer.parseInt(jTextProdutorBSex.getText());

        if (qtd_seg >= 0 || qtd_ter >= 0 || qtd_qua >= 0 || qtd_qui >= 0 || qtd_sex >= 0) {
            conDB.AdicionarProducaoSemanal(produtor, produto, qtd_seg, qtd_ter, qtd_qua, qtd_qui, qtd_sex, getWeekofYear, ano);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsProducaoSemanal.this, "Quantidade tem que ser superior ou igual a 0(zero) em alguma semana");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:

        closeApplication();

    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        ListaProducaoSemanal preEnco = new ListaProducaoSemanal();
        preEnco.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBoxProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto1ActionPerformed
        produtoselectedA = jComboBoxProduto1.getSelectedIndex() + 1;
        produtorSelected = 1;
        if (iA > 0) {
            DoConnectA();
        }
        iA++;


    }//GEN-LAST:event_jComboBoxProduto1ActionPerformed

    private void jBtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaActionPerformed
        // TODO add your handling code here:
        ano = Integer.parseInt((String) jComboBoxAno.getSelectedItem());
        getWeekofYear = Integer.parseInt((String) jComboBoxWeek.getSelectedItem());
        DoConnect();
    }//GEN-LAST:event_jBtnPesquisaActionPerformed

    private void jComboBoxProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto5ActionPerformed
        produtoselectedA = jComboBoxProduto5.getSelectedIndex() + 1;
        produtorSelected = 5;
        if (iE > 0) {
            DoConnectA();
        }
        iE++;
    }//GEN-LAST:event_jComboBoxProduto5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

   }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBoxProduto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto9ActionPerformed
        if (jCheckBox1.isSelected() && iJ != 0) {

            produtoselectedA = jComboBoxProduto9.getSelectedIndex() + 1;
            jComboBoxProduto1.setSelectedIndex(produtoselectedA - 1);
            jComboBoxProduto2.setSelectedIndex(produtoselectedA - 1);
            jComboBoxProduto3.setSelectedIndex(produtoselectedA - 1);
            jComboBoxProduto4.setSelectedIndex(produtoselectedA - 1);
            jComboBoxProduto5.setSelectedIndex(produtoselectedA - 1);
             DoConnectB();
        }
        iJ++;
    }//GEN-LAST:event_jComboBoxProduto9ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        int produtor = 5;
        
        jButton23.setEnabled(false);

        String produto = (String) jComboBoxProduto5.getSelectedItem();

        int qtd_seg = Integer.parseInt(jTextProdutorESeg.getText());
        int qtd_ter = Integer.parseInt(jTextProdutorETer.getText());
        int qtd_qua = Integer.parseInt(jTextProdutorEQua.getText());
        int qtd_qui = Integer.parseInt(jTextProdutorEQui.getText());
        int qtd_sex = Integer.parseInt(jTextProdutorESex.getText());

        if (qtd_seg >= 0 || qtd_ter >= 0 || qtd_qua >= 0 || qtd_qui >= 0 || qtd_sex >= 0) {
            conDB.AdicionarProducaoSemanal(produtor, produto, qtd_seg, qtd_ter, qtd_qua, qtd_qui, qtd_sex, getWeekofYear, ano);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsProducaoSemanal.this, "Quantidade tem que ser superior ou igual a 0(zero) em alguma semana");
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        int produtor = 4;
        
        jButton22.setEnabled(false);

        String produto = (String) jComboBoxProduto4.getSelectedItem();

        int qtd_seg = Integer.parseInt(jTextProdutorDSeg.getText());
        int qtd_ter = Integer.parseInt(jTextProdutorDTer.getText());
        int qtd_qua = Integer.parseInt(jTextProdutorDQua.getText());
        int qtd_qui = Integer.parseInt(jTextProdutorDQui.getText());
        int qtd_sex = Integer.parseInt(jTextProdutorDSex.getText());

        if (qtd_seg >= 0 || qtd_ter >= 0 || qtd_qua >= 0 || qtd_qui >= 0 || qtd_sex >= 0) {
            conDB.AdicionarProducaoSemanal(produtor, produto, qtd_seg, qtd_ter, qtd_qua, qtd_qui, qtd_sex, getWeekofYear, ano);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsProducaoSemanal.this, "Quantidade tem que ser superior ou igual a 0(zero) em alguma semana");
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jComboBoxProduto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProduto4ActionPerformed
        produtoselectedA = jComboBoxProduto4.getSelectedIndex() + 1;
        produtorSelected = 4;
        if (iD > 0) {
            DoConnectA();
        }
        iD++;
    }//GEN-LAST:event_jComboBoxProduto4ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        int produtor = 3;
        
        jButton21.setEnabled(false);
        
        String produto = (String) jComboBoxProduto3.getSelectedItem();

        int qtd_seg = Integer.parseInt(jTextProdutorCSeg.getText());
        int qtd_ter = Integer.parseInt(jTextProdutorCTer.getText());
        int qtd_qua = Integer.parseInt(jTextProdutorCQua.getText());
        int qtd_qui = Integer.parseInt(jTextProdutorCQui.getText());
        int qtd_sex = Integer.parseInt(jTextProdutorCSex.getText());

        if (qtd_seg >= 0 || qtd_ter >= 0 || qtd_qua >= 0 || qtd_qui >= 0 || qtd_sex >= 0) {
            conDB.AdicionarProducaoSemanal(produtor, produto, qtd_seg, qtd_ter, qtd_qua, qtd_qui, qtd_sex, getWeekofYear, ano);
        } else {
            javax.swing.JOptionPane.showMessageDialog(FormsProducaoSemanal.this, "Quantidade tem que ser superior ou igual a 0(zero) em alguma semana");
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jComboBoxWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWeekActionPerformed

    private void jComboBoxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnoActionPerformed

    private void jTextProdutorASegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorASegKeyPressed
        jButton19.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorASegKeyPressed

    private void jTextProdutorATerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorATerKeyPressed
         jButton19.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorATerKeyPressed

    private void jTextProdutorAQuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorAQuaKeyPressed
       jButton19.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorAQuaKeyPressed

    private void jTextProdutorAQuiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorAQuiKeyPressed
       jButton19.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorAQuiKeyPressed

    private void jTextProdutorASexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorASexKeyPressed
jButton19.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorASexKeyPressed

    private void jTextProdutorBSegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorBSegKeyPressed
        jButton20.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorBSegKeyPressed

    private void jTextProdutorBTerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorBTerKeyPressed
jButton20.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorBTerKeyPressed

    private void jTextProdutorBQuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorBQuaKeyPressed
       jButton20.setEnabled(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorBQuaKeyPressed

    private void jTextProdutorBQuiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorBQuiKeyPressed
        jButton20.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorBQuiKeyPressed

    private void jTextProdutorBSexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorBSexKeyPressed
         jButton20.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorBSexKeyPressed

    private void jTextProdutorCSegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorCSegKeyPressed
         jButton21.setEnabled(true);
    }//GEN-LAST:event_jTextProdutorCSegKeyPressed

    private void jTextProdutorCTerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorCTerKeyPressed
 jButton21.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorCTerKeyPressed

    private void jTextProdutorCQuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorCQuaKeyPressed
 jButton21.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorCQuaKeyPressed

    private void jTextProdutorCQuiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorCQuiKeyPressed
 jButton21.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorCQuiKeyPressed

    private void jTextProdutorCSexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorCSexKeyPressed
 jButton21.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorCSexKeyPressed

    private void jTextProdutorDSegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorDSegKeyPressed
        jButton22.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorDSegKeyPressed

    private void jTextProdutorDTerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorDTerKeyPressed
jButton22.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorDTerKeyPressed

    private void jTextProdutorDQuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorDQuaKeyPressed
jButton22.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorDQuaKeyPressed

    private void jTextProdutorDQuiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorDQuiKeyPressed
jButton22.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorDQuiKeyPressed

    private void jTextProdutorDSexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorDSexKeyPressed
jButton22.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorDSexKeyPressed

    private void jTextProdutorESegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorESegKeyPressed
jButton23.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorESegKeyPressed

    private void jTextProdutorETerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorETerKeyPressed
jButton23.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorETerKeyPressed

    private void jTextProdutorEQuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorEQuaKeyPressed
jButton23.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorEQuaKeyPressed

    private void jTextProdutorEQuiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorEQuiKeyPressed
jButton23.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorEQuiKeyPressed

    private void jTextProdutorESexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextProdutorESexKeyPressed
jButton23.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jTextProdutorESexKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsProducaoSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsProducaoSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsProducaoSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsProducaoSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormsProducaoSemanal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton jBtnPesquisa;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JComboBox jComboBoxProduto1;
    private javax.swing.JComboBox jComboBoxProduto2;
    private javax.swing.JComboBox jComboBoxProduto3;
    private javax.swing.JComboBox jComboBoxProduto4;
    private javax.swing.JComboBox jComboBoxProduto5;
    private javax.swing.JComboBox jComboBoxProduto9;
    private javax.swing.JComboBox jComboBoxWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelSemana;
    private javax.swing.JTextField jTextProdutorAQua;
    private javax.swing.JTextField jTextProdutorAQui;
    private javax.swing.JTextField jTextProdutorASeg;
    private javax.swing.JTextField jTextProdutorASex;
    private javax.swing.JTextField jTextProdutorATer;
    private javax.swing.JTextField jTextProdutorBQua;
    private javax.swing.JTextField jTextProdutorBQui;
    private javax.swing.JTextField jTextProdutorBSeg;
    private javax.swing.JTextField jTextProdutorBSex;
    private javax.swing.JTextField jTextProdutorBTer;
    private javax.swing.JTextField jTextProdutorCQua;
    private javax.swing.JTextField jTextProdutorCQui;
    private javax.swing.JTextField jTextProdutorCSeg;
    private javax.swing.JTextField jTextProdutorCSex;
    private javax.swing.JTextField jTextProdutorCTer;
    private javax.swing.JTextField jTextProdutorDQua;
    private javax.swing.JTextField jTextProdutorDQui;
    private javax.swing.JTextField jTextProdutorDSeg;
    private javax.swing.JTextField jTextProdutorDSex;
    private javax.swing.JTextField jTextProdutorDTer;
    private javax.swing.JTextField jTextProdutorEQua;
    private javax.swing.JTextField jTextProdutorEQui;
    private javax.swing.JTextField jTextProdutorESeg;
    private javax.swing.JTextField jTextProdutorESex;
    private javax.swing.JTextField jTextProdutorETer;
    // End of variables declaration//GEN-END:variables

    private void DoConnect() {
         try {
            
            String host = "jdbc:mysql://localhost:3306/daquinta_teste";
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM produtos";
            rs = stmt.executeQuery(sql);
            
            
            
            rs.next();
            
 
            
           //Listagem dos Produtos
            
            rs.beforeFirst();
             if (variavelControlNomeProdutos==false) {
                while (rs.next()){  
                    jComboBoxProduto1.addItem(rs.getString("Nome"));
                    jComboBoxProduto2.addItem(rs.getString("Nome"));
                    jComboBoxProduto3.addItem(rs.getString("Nome"));
                    jComboBoxProduto4.addItem(rs.getString("Nome"));
                    jComboBoxProduto5.addItem(rs.getString("Nome"));  
                    jComboBoxProduto9.addItem(rs.getString("Nome"));    
                }   
                variavelControlNomeProdutos=true;
            }
             else {
                 jComboBoxProduto1.setSelectedIndex(0);
                 jComboBoxProduto2.setSelectedIndex(0);
                 jComboBoxProduto3.setSelectedIndex(0);
                 jComboBoxProduto4.setSelectedIndex(0);;
                 jComboBoxProduto5.setSelectedIndex(0); 
                 jComboBoxProduto9.setSelectedIndex(0);
             }
             //Restaurante A
            stmt2 = con.createStatement();
            String sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) "
                    + "FROM " + dbName + ".producao_semanal WHERE getWeekofYear="+getWeekofYear+" AND "
                    + "YEAR(" + dbName + ".producao_semanal.data) ='" + ano+"' AND produtores_idprodutores=1";
            ResultSet rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
           
                while (rs2.next()){  
                    jTextProdutorASeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                    jTextProdutorATer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                    jTextProdutorAQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                    jTextProdutorAQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                    jTextProdutorASex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));  

                }   
             

            rs2.close();
            //Restaurante B
            sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+getWeekofYear+" AND "
                    + "YEAR(" + dbName + ".producao_semanal.data) ='" + ano+"' AND produtores_idprodutores=2 "
                    + "AND produtos_idprodutos='"+produtoselectedA+"'";
            rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana B
            
            rs2.beforeFirst();
             while (rs2.next()){  
                jTextProdutorBSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorBTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorBQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorBQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorBSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));  
                
            }   
             
            rs2.close();
            //Restaurante C
            sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) "
                    + "FROM " + dbName + ".producao_semanal WHERE getWeekofYear="+getWeekofYear+" "
                    + "AND YEAR(" + dbName + ".producao_semanal.data) ='" + ano+"' AND produtores_idprodutores=3";
            rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana C
            
            rs2.beforeFirst();
             while (rs2.next()){  
                jTextProdutorCSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorCTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorCQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorCQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorCSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));  
                
            }   
             
            rs2.close();
            
            //Restaurante D
            
            sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) "
                    + "FROM " + dbName + ".producao_semanal WHERE getWeekofYear="
                    + ""+getWeekofYear+" AND YEAR(" + dbName + ".producao_semanal.data) ='" + 
                    ano+"' AND produtores_idprodutores=4";
            rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana D
            
            rs2.beforeFirst();
             while (rs2.next()){  
                jTextProdutorDSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorDTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorDQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorDQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorDSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));  
                
            }   
             
            rs2.close();
            
            //Restaurante E
            sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) "
                    + "FROM " + dbName + ".producao_semanal WHERE getWeekofYear="+getWeekofYear+" "
                    + "AND YEAR(" + dbName + ".producao_semanal.data) ='" + ano+"' AND produtores_idprodutores=5";
            rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana E
            
            rs2.beforeFirst();
             while (rs2.next()){  
                jTextProdutorESeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorETer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorEQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorEQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorESex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));  
                
            }   
             
            rs2.close();
            
            
            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsProducaoSemanal.this, err.getMessage());
        }
    }

    private void closeApplication() {
        dispose();
    }

    private void DoConnectA() {
        try{
            
            //Restaurante A
            if (produtorSelected == 1) {
                jTextProdutorASeg.setText("");
                jTextProdutorATer.setText("");  
                jTextProdutorAQua.setText("");  
                jTextProdutorAQui.setText("");  
                jTextProdutorASex.setText("");
            }
             if (produtorSelected == 2) {
                jTextProdutorBSeg.setText("");
                jTextProdutorBTer.setText("");  
                jTextProdutorBQua.setText("");  
                jTextProdutorBQui.setText("");  
                jTextProdutorBSex.setText("");
            }
              if (produtorSelected == 3) {
                jTextProdutorCSeg.setText("");
                jTextProdutorCTer.setText("");  
                jTextProdutorCQua.setText("");  
                jTextProdutorCQui.setText("");  
                jTextProdutorCSex.setText("");
            }
               if (produtorSelected == 4) {
                jTextProdutorDSeg.setText("");
                jTextProdutorDTer.setText("");  
                jTextProdutorDQua.setText("");  
                jTextProdutorDQui.setText("");  
                jTextProdutorDSex.setText("");
            }
                if (produtorSelected == 5) {
                jTextProdutorESeg.setText("");
                jTextProdutorETer.setText("");  
                jTextProdutorEQua.setText("");  
                jTextProdutorEQui.setText("");  
                jTextProdutorESex.setText("");
            }
            
            
            String sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+ getWeekofYear
                    + " AND YEAR(" + dbName + ".producao_semanal.data) ='"+ano+"' AND produtores_idprodutores=" + produtorSelected
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            ResultSet rs2 = stmt.executeQuery(sql1);
                       
            
            rs2.next();
            
          
           //Listagem dos Produtos por semana A
            
            rs2.beforeFirst();
            while (rs2.next()){  
                if (produtorSelected == 1) {
                    jTextProdutorASeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                    jTextProdutorATer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                    jTextProdutorAQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                    jTextProdutorAQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                    jTextProdutorASex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
                }
                if (produtorSelected == 2) {
                    jTextProdutorBSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                    jTextProdutorBTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                    jTextProdutorBQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                    jTextProdutorBQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                    jTextProdutorBSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
                }
                if (produtorSelected == 3) {
                    jTextProdutorCSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                    jTextProdutorCTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                    jTextProdutorCQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                    jTextProdutorCQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                    jTextProdutorCSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
                }
                if (produtorSelected == 4) {
                    jTextProdutorDSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                    jTextProdutorDTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                    jTextProdutorDQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                    jTextProdutorDQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                    jTextProdutorDSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
                }
                if (produtorSelected == 5) {
                    jTextProdutorESeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                    jTextProdutorETer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                    jTextProdutorEQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                    jTextProdutorEQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                    jTextProdutorESex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
                }
                
            }   
             
            rs2.close();
             }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsProducaoSemanal.this, err.getMessage());
        }
    }

    private void DoConnectB() {
        try{
            
            //Restaurante A
            
                jTextProdutorASeg.setText("");
                jTextProdutorATer.setText("");  
                jTextProdutorAQua.setText("");  
                jTextProdutorAQui.setText("");  
                jTextProdutorASex.setText("");
                jTextProdutorBSeg.setText("");
                jTextProdutorBTer.setText("");  
                jTextProdutorBQua.setText("");  
                jTextProdutorBQui.setText("");  
                jTextProdutorBSex.setText("");
                jTextProdutorCSeg.setText("");
                jTextProdutorCTer.setText("");  
                jTextProdutorCQua.setText("");  
                jTextProdutorCQui.setText("");  
                jTextProdutorCSex.setText("");
                jTextProdutorDSeg.setText("");
                jTextProdutorDTer.setText("");  
                jTextProdutorDQua.setText("");  
                jTextProdutorDQui.setText("");  
                jTextProdutorDSex.setText("");
                jTextProdutorESeg.setText("");
                jTextProdutorETer.setText("");  
                jTextProdutorEQua.setText("");  
                jTextProdutorEQui.setText("");  
                jTextProdutorESex.setText("");
                
            
          
           //Restaurantes A
           String sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+ getWeekofYear
                    + " AND YEAR(" + dbName + ".producao_semanal.data) ='"+ano+"' AND produtores_idprodutores=1"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            ResultSet rs2 = stmt.executeQuery(sql1);
           
           rs2.next();
           rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorASeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorATer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorAQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorAQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorASex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
            }   
            rs2.close();
            //Restaurantes B
           sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+ getWeekofYear
                    + " AND YEAR(" + dbName + ".producao_semanal.data) ='"+ano+"' AND produtores_idprodutores=2"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
           
           rs2.next();
           rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorBSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorBTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorBQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorBQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorBSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
            }   
            rs2.close();
            //Restaurantes C
           sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+ getWeekofYear
                    + " AND YEAR(" + dbName + ".producao_semanal.data) ='"+ano+"' AND produtores_idprodutores=3"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
           
           rs2.next();
           rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorCSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorCTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorCQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorCQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorCSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
            }   
            rs2.close();
            //Restaurantes D
           sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+ getWeekofYear
                    + " AND YEAR(" + dbName + ".producao_semanal.data) ='"+ano+"' AND produtores_idprodutores=4"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
           
           rs2.next();
           rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorDSeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorDTer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorDQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorDQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorDSex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
            }   
            rs2.close();
            //Restaurantes E
           sql1 = "SELECT SUM(qtdseg),SUM(qtdter),SUM(qtdqua),SUM(qtdqui),SUM(qtdsex) FROM "
                    + "" + dbName + ".producao_semanal WHERE getWeekofYear="+ getWeekofYear
                    + " AND YEAR(" + dbName + ".producao_semanal.data) ='"+ano+"' AND produtores_idprodutores=5"
                    + " AND produtos_idprodutos="+produtoselectedA;
            
            rs2 = stmt.executeQuery(sql1);
           
           rs2.next();
           rs2.beforeFirst();
            while (rs2.next()){  
                jTextProdutorESeg.setText(Integer.toString(rs2.getInt("SUM(qtdseg)")));  
                jTextProdutorETer.setText(Integer.toString(rs2.getInt("SUM(qtdter)")));  
                jTextProdutorEQua.setText(Integer.toString(rs2.getInt("SUM(qtdqua)")));  
                jTextProdutorEQui.setText(Integer.toString(rs2.getInt("SUM(qtdqui)")));  
                jTextProdutorESex.setText(Integer.toString(rs2.getInt("SUM(qtdsex)")));   
            }   
            rs2.close();
            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsProducaoSemanal.this, err.getMessage());
        }
    }
}
