/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Toshiba
 */
public class FormsRestaurantes extends javax.swing.JFrame {

    /**
     * Creates new form FormsRestaurantes
     */
    static String dbName = "daquinta_teste"; //Nome do Banco criado
    String restaurante;
    Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;
    int IDs = 1;
    DB conDB = new DB();
    private int totalidade=0;
    boolean editar = false, criarnovo=false;
    
    public FormsRestaurantes() {
        initComponents();
        jCheckBox1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(false);
        DoConnect();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textIDRestaurante = new javax.swing.JTextField();
        textNomeRestaurante = new javax.swing.JTextField();
        textMoradaRestaurante = new javax.swing.JTextField();
        textTelefoneRestaurante = new javax.swing.JTextField();
        textNIFRestaurante = new javax.swing.JTextField();
        textGPSRestaurante = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        btnUpdateRecord = new javax.swing.JButton();
        btnSaveRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnSaveRecord1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textHistoricoRestaurante = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurantes");
        setResizable(false);

        jLabel1.setText("ID:");

        jLabel2.setText("Nome");

        jLabel3.setText("Morada");

        jLabel4.setText("NIF");

        jLabel5.setText("Coordenadas GPS");

        jLabel6.setText("Notas");

        jLabel7.setText("Telefone");

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/92.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/99.png"))); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/98.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/94.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/8.png"))); // NOI18N
        btnNewRecord.setText("Novo");
        btnNewRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnNewRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnUpdateRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/2.png"))); // NOI18N
        btnUpdateRecord.setText("Editar");
        btnUpdateRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnUpdateRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        btnSaveRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/7.png"))); // NOI18N
        btnSaveRecord.setText("Guardar");
        btnSaveRecord.setEnabled(false);
        btnSaveRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/9.png"))); // NOI18N
        btnDeleteRecord.setText("Eliminar");
        btnDeleteRecord.setMaximumSize(new java.awt.Dimension(111, 41));
        btnDeleteRecord.setMinimumSize(new java.awt.Dimension(111, 41));
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/120.png"))); // NOI18N
        jLabel9.setText("Clientes | Restaurantes");

        btnSaveRecord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnSaveRecord1.setText("Cancelar");
        btnSaveRecord1.setMaximumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord1.setMinimumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecord1ActionPerformed(evt);
            }
        });

        textHistoricoRestaurante.setColumns(20);
        textHistoricoRestaurante.setRows(5);
        jScrollPane2.setViewportView(textHistoricoRestaurante);

        jCheckBox1.setText("Receber na Totalidade");

        jRadioButton1.setText("Setubal");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Palmela");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textMoradaRestaurante))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textNomeRestaurante))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textGPSRestaurante))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textTelefoneRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textNIFRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(jRadioButton1)))
                                        .addGap(0, 83, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnDeleteRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdateRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNewRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSaveRecord1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSaveRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(textIDRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(jRadioButton2)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textIDRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textMoradaRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textTelefoneRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textNIFRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textGPSRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLast, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFirst)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(282, Short.MAX_VALUE)
                    .addComponent(jRadioButton2)
                    .addGap(220, 220, 220)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setSelected(false);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        try {
            if (rs.next()){
                btnLast.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(true);
                btnFirst.setEnabled(true);
                int id_col = rs.getInt("idrestaurantes");
                String Name = rs.getString("nome");
                String Morada = rs.getString("morada");
                int Telefone = rs.getInt("telefone");
                int NIF = rs.getInt("nif");
                String GPS = rs.getString("gps");
                String Historico = rs.getString("notas");

                textIDRestaurante.setText(Integer.toString(id_col));
                textNomeRestaurante.setText(Name);
                textMoradaRestaurante.setText(Morada);
                textTelefoneRestaurante.setText(Integer.toString(Telefone));     
                textNIFRestaurante.setText(Integer.toString(NIF)); 
                textGPSRestaurante.setText(GPS); 
                textHistoricoRestaurante.setText(Historico); 
                if(rs.getInt("totalidadeEncomenda")==1) jCheckBox1.setSelected(true);
                if(rs.getInt("localizacao")==1) 
                {
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                }
                if(rs.getInt("localizacao")==2) 
                {
                     jRadioButton1.setSelected(false);
                     jRadioButton2.setSelected(true);
                }
            }
            else {
                rs.previous();
                btnLast.setEnabled(false);
                btnNext.setEnabled(false);
                btnPrevious.setEnabled(true);
                btnFirst.setEnabled(true);
                 JOptionPane.showMessageDialog(FormsRestaurantes.this, "Não existem mais Clientes");
            }
        }
        catch(SQLException err) {
            JOptionPane.showMessageDialog(FormsRestaurantes.this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setSelected(false);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        try {
            if (rs.previous()){
                btnLast.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(true);
                btnFirst.setEnabled(true);
                int id_col = rs.getInt("idrestaurantes");
                String Name = rs.getString("nome");
                String Morada = rs.getString("morada");
                int Telefone = rs.getInt("telefone");
                int NIF = rs.getInt("nif");
                String GPS = rs.getString("gps");
                String Historico = rs.getString("notas");

                textIDRestaurante.setText(Integer.toString(id_col));
                textNomeRestaurante.setText(Name);
                textMoradaRestaurante.setText(Morada);
                textTelefoneRestaurante.setText(Integer.toString(Telefone));     
                textNIFRestaurante.setText(Integer.toString(NIF)); 
                textGPSRestaurante.setText(GPS); 
                textHistoricoRestaurante.setText(Historico); 
                if(rs.getInt("totalidadeEncomenda")==1) jCheckBox1.setSelected(true);
               if(rs.getInt("localizacao")==1) 
                {
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                }
                if(rs.getInt("localizacao")==2) 
                {
                     jRadioButton1.setSelected(false);
                     jRadioButton2.setSelected(true);
                }
            }
            else {
                rs.next();
                btnLast.setEnabled(true);
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(false);
                btnFirst.setEnabled(false);
                JOptionPane.showMessageDialog(FormsRestaurantes.this, "Inicio!");
            }
    
        }
        catch(SQLException err) {
            
            JOptionPane.showMessageDialog(FormsRestaurantes.this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        btnFirst.setEnabled(true);
        btnNext.setEnabled(true);
        btnPrevious.setEnabled(false);
        btnFirst.setEnabled(false);
        jCheckBox1.setSelected(false);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        try{
            rs.first();
            int id_col = rs.getInt("idrestaurantes");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");

            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));     
            textNIFRestaurante.setText(Integer.toString(NIF)); 
            textGPSRestaurante.setText(GPS); 
            textHistoricoRestaurante.setText(Historico); 
            if(rs.getInt("totalidadeEncomenda")==1) jCheckBox1.setSelected(true);
            if(rs.getInt("localizacao")==1) 
                {
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                }
                if(rs.getInt("localizacao")==2) 
                {
                     jRadioButton1.setSelected(false);
                     jRadioButton2.setSelected(true);
                }
               
        }
        catch(SQLException err) {
            JOptionPane.showMessageDialog(FormsRestaurantes.this, err.getMessage());
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setSelected(false);
        btnLast.setEnabled(false);
        btnNext.setEnabled(false);
        btnPrevious.setEnabled(true);
        btnFirst.setEnabled(true);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        try{
            
            rs.last();
            int id_col = rs.getInt("idrestaurantes");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");

            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));     
            textNIFRestaurante.setText(Integer.toString(NIF)); 
            textGPSRestaurante.setText(GPS); 
            textHistoricoRestaurante.setText(Historico); 
            if(rs.getInt("totalidadeEncomenda")==1) jCheckBox1.setSelected(true);
            if(rs.getInt("localizacao")==1) 
                {
                    jRadioButton1.setSelected(true);
                    jRadioButton2.setSelected(false);
                }
                if(rs.getInt("localizacao")==2) 
                {
                     jRadioButton1.setSelected(false);
                     jRadioButton2.setSelected(true);
                }
        }
        catch(SQLException err) {
            JOptionPane.showMessageDialog(FormsRestaurantes.this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
        // TODO add your handling code here:
        
        try {
            btnSaveRecord.setEnabled(true);
            criarnovo = true;
            editar = false;
            textIDRestaurante.setEnabled(true);
            textNomeRestaurante.setEnabled(true);
            textMoradaRestaurante.setEnabled(true);
            textTelefoneRestaurante.setEnabled(true);   
            textNIFRestaurante.setEnabled(true);
            textGPSRestaurante.setEnabled(true);
            textHistoricoRestaurante.setEnabled(true);
            jCheckBox1.setSelected(false);
            
            rs.last();
            int id_col = rs.getInt("idrestaurantes");
            //curRow = rs.getRow();
            textIDRestaurante.setEnabled(false);
            textIDRestaurante.setText(Integer.toString(id_col+1));
            textNomeRestaurante.setText(" ");
            textMoradaRestaurante.setText(" ");
            textTelefoneRestaurante.setText("1");     
            textNIFRestaurante.setText("1"); 
            textGPSRestaurante.setText(" ");
            textHistoricoRestaurante.setText(" ");
            
            btnFirst.setEnabled( false );
            btnPrevious.setEnabled( false ) ;
            btnNext.setEnabled( false );
            btnLast.setEnabled( false );
            btnUpdateRecord.setEnabled( false );
            btnDeleteRecord.setEnabled( false );
            btnNewRecord.setEnabled( false );

            btnSaveRecord.setEnabled( true );
            
        }
        catch (SQLException err) {
            System.out.println(err.getMessage() );
        }
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        // TODO add your handling code here:
        try {
            btnSaveRecord.setEnabled(true);
            editar = true;
            textIDRestaurante.setEnabled(false);
            textNomeRestaurante.setEnabled(true);
            textMoradaRestaurante.setEnabled(true);
            textTelefoneRestaurante.setEnabled(true);   
            textNIFRestaurante.setEnabled(true);
            textGPSRestaurante.setEnabled(true);
            textHistoricoRestaurante.setEnabled(true);
            int id_col = rs.getInt("idrestaurantes");
            //curRow = rs.getRow();
            
        }
        catch (SQLException err) {
            System.out.println(err.getMessage() );
        }
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed
        // TODO add your handling code here:
            System.out.println("A Guardar");  
            int localizacao=0;
            int ID = Integer.valueOf(textIDRestaurante.getText());
            String Name = textNomeRestaurante.getText();
            String Morada = textMoradaRestaurante.getText();
            int Telefone = Integer.valueOf(textTelefoneRestaurante.getText());
            int NIF = Integer.valueOf(textNIFRestaurante.getText());
            String GPS = textGPSRestaurante.getText();
            String Historico = textHistoricoRestaurante.getText();
            if (jCheckBox1.isSelected()) totalidade=1;
            if(jRadioButton1.isSelected()) localizacao = 1;
            if(jRadioButton2.isSelected()) localizacao = 2;      
                    
            
            if (criarnovo==true){ //Is new
                System.out.println("Novo");
                criarnovo=false;
                conDB.inserirRestauranteNovo(Name, Morada,Telefone,NIF,GPS,Historico,totalidade, localizacao);
            }
            else if (editar==true) {
                System.out.println("Editar Restaurante: " + ID);
                editar=false;
                conDB.inserirRestauranteEditar(ID, Name, Morada,Telefone,NIF,GPS,Historico,totalidade, localizacao);
            }
               
            
       
            
            btnFirst.setEnabled( true );
            btnPrevious.setEnabled( true ) ;
            btnNext.setEnabled( true );
            btnLast.setEnabled( true );
            btnUpdateRecord.setEnabled( true );
            btnDeleteRecord.setEnabled( true );
            btnNewRecord.setEnabled( true );
            
            btnSaveRecord.setEnabled(false);
            
            JOptionPane.showMessageDialog(FormsRestaurantes.this, "Guardado");
             
     
    }//GEN-LAST:event_btnSaveRecordActionPerformed

    private void btnSaveRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecord1ActionPerformed
        // TODO add your handling code here:
         if (criarnovo==true){ //Is new
                criarnovo=false;
                btnFirst.setEnabled( true );
                btnPrevious.setEnabled( true ) ;
                btnNext.setEnabled( true );
                btnLast.setEnabled( true );
                btnUpdateRecord.setEnabled( true );
                btnDeleteRecord.setEnabled( true );
                btnNewRecord.setEnabled( true );

            btnSaveRecord.setEnabled( true );
            }
            else if (editar==true) {
                editar=false;
                btnFirst.setEnabled( true );
                btnPrevious.setEnabled( true ) ;
                btnNext.setEnabled( true );
                btnLast.setEnabled( true );
                btnUpdateRecord.setEnabled( true );
                btnDeleteRecord.setEnabled( true );
                btnNewRecord.setEnabled( true );
            } else {
                closeApplication();
            }
                
            
                    
    }//GEN-LAST:event_btnSaveRecord1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        jRadioButton2.setSelected(true);
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormsRestaurantes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JButton btnSaveRecord1;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textGPSRestaurante;
    private javax.swing.JTextArea textHistoricoRestaurante;
    private javax.swing.JTextField textIDRestaurante;
    private javax.swing.JTextField textMoradaRestaurante;
    private javax.swing.JTextField textNIFRestaurante;
    private javax.swing.JTextField textNomeRestaurante;
    private javax.swing.JTextField textTelefoneRestaurante;
    // End of variables declaration//GEN-END:variables

    private void DoConnect() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/" + dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM restaurantes";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            int id_col = rs.getInt("idrestaurantes");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");
            if(rs.getInt("totalidadeEncomenda")==1) jCheckBox1.setSelected(true);
            if(rs.getInt("localizacao")==1) jRadioButton1.setSelected(true);
            if(rs.getInt("localizacao")==2) jRadioButton2.setSelected(true);
            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));     
            textNIFRestaurante.setText(Integer.toString(NIF)); 
            textGPSRestaurante.setText(GPS); 
            textHistoricoRestaurante.setText(Historico); 
            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsRestaurantes.this, err.getMessage());
        }
    }
    private void closeApplication() {
        dispose();
    }

    void setUser(String jtext1) {
        restaurante = jtext1;

        DoConnect2();
   
    }

    private void DoConnect2() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/" + dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM restaurantes WHERE nome='"+restaurante+"'";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            int id_col = rs.getInt("idrestaurantes");
            String Name = rs.getString("nome");
            String Morada = rs.getString("morada");
            int Telefone = rs.getInt("telefone");
            int NIF = rs.getInt("nif");
            String GPS = rs.getString("gps");
            String Historico = rs.getString("notas");
            
            textIDRestaurante.setText(Integer.toString(id_col));
            textNomeRestaurante.setText(Name);
            textMoradaRestaurante.setText(Morada);
            textTelefoneRestaurante.setText(Integer.toString(Telefone));     
            textNIFRestaurante.setText(Integer.toString(NIF)); 
            textGPSRestaurante.setText(GPS); 
            textHistoricoRestaurante.setText(Historico); 
            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(FormsRestaurantes.this, err.getMessage());
        }
    }
}
