/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class ListaTransportes extends javax.swing.JFrame {

    /**
     * Creates new form ListaTransportes
     */
    static String dbName = "daquinta_teste"; //Nome do Banco criado
    
     Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;
    int IDs = 1;
    DB conDB = new DB();
    boolean editar = false;
    JList list = new JList();
    DefaultListModel modelComFrigorifico = new DefaultListModel(); //create a new list model
    DefaultListModel modelSemFrigorifico = new DefaultListModel(); 
            
    public ListaTransportes() {
        initComponents();
        DoConnect();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSaveRecord1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listComFrigorifico = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transportes");
        setResizable(false);

        btnSaveRecord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnSaveRecord1.setText("Cancelar");
        btnSaveRecord1.setMaximumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord1.setMinimumSize(new java.awt.Dimension(111, 41));
        btnSaveRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecord1ActionPerformed(evt);
            }
        });

        listComFrigorifico.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listComFrigorifico);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/66.png"))); // NOI18N
        jLabel9.setText("Transportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaveRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecord1ActionPerformed
        // TODO add your handling code here:

        closeApplication();



    }//GEN-LAST:event_btnSaveRecord1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListaTransportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveRecord1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList listComFrigorifico;
    // End of variables declaration//GEN-END:variables

    private void DoConnect() {
        try {
            
            String host = "jdbc:mysql://localhost:3306/" + dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            String sql = "SELECT * FROM transportes";
            rs = stmt.executeQuery(sql);
            
            int Tipo;
            
            rs.next();
            rs.beforeFirst();
            
            while (rs.next()){  
               String ItemList1 = rs.getString("matricula"); //get the element in column "item_code"
               modelComFrigorifico.addElement(ItemList1); //add each item to the model
             }   
        
            listComFrigorifico.setModel(modelComFrigorifico);
           
            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(ListaTransportes.this, err.getMessage());
        }
    }

    private void closeApplication() {
        dispose();
    }
}
