/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daquinta;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class ListaPreEncomendas extends javax.swing.JFrame {

    /**
     * Creates new form ListaPreEncomendas
     */
    
    Connection con, con2;
    Statement stmt, stmt2;
    
    static String dbName = "daquinta_teste"; //Nome do Banco criado
     
    int curRow = 0;
    int IDs = 1;
    int totalProdutos, totalRestaurantes;
    String []totalNomesProdutos;
    Integer []totalQuantidadeProdutos;
    String [] RAItemList, RBItemList,RCItemList,RDItemList,REItemList,RFItemList,RGItemList,RHItemList;
    Integer[] RAItemList2, RBItemList2,RCItemList2,RDItemList2,REItemList2,RFItemList2,RGItemList2,RHItemList2 ;
    DB conDB = new DB();
    boolean editar = false, criarnovo=false;
    //data 
           java.util.Date date = new java.util.Date();
           java.util.Date date2 = new java.util.Date();
    
            
    
         
    Integer ano=date.getYear()+1900;
    
   
     DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
   
    
    Calendar cal = Calendar.getInstance();
     Calendar calUk = Calendar.getInstance(Locale.UK);  
    
   
    
    
    JComboBox cbIdDisciplina, cbDisciplina; 
    
   
    ResultSet rs, rsProdutos;
   
    
    int restaurante;

   
        
       
     
    
    
    public ListaPreEncomendas() {
        initComponents();
        DoConnect();
        setLocationRelativeTo(null);
         Integer get = calUk.get( Calendar.WEEK_OF_YEAR );
        jLabelSemana.setText(get.toString());
        jLabelData.setText(dateFormat.format(date).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProdutosRestauranteA = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListProdutosRestauranteB = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListProdutosRestauranteD = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListProdutosRestauranteE = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jListProdutosRestauranteG = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jListProdutosRestauranteH = new javax.swing.JList();
        btnCancel = new javax.swing.JButton();
        jComboBoxAno = new javax.swing.JComboBox();
        jBtnPesquisa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListProdutosRestauranteC = new javax.swing.JList();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jListProdutosRestauranteF = new javax.swing.JList();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jListProdutosRestauranteTotais = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelSemana = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista das Pré-Encomendas");
        setResizable(false);

        jLabel1.setText("Centro Social de Palmela");

        jScrollPane1.setViewportView(jListProdutosRestauranteA);

        jLabel5.setText("Restaurante “O Parque”");

        jScrollPane4.setViewportView(jListProdutosRestauranteB);

        jLabel9.setText("Restaurante “Três15Dias”");

        jScrollPane7.setViewportView(jListProdutosRestauranteD);

        jLabel10.setText("Restaurante “D. Isilda”");

        jScrollPane8.setViewportView(jListProdutosRestauranteE);

        jLabel12.setText("Restaurante D");

        jLabel14.setText("Vale dos Pintassilgos");

        jScrollPane9.setViewportView(jListProdutosRestauranteG);

        jLabel16.setText("Santa Casa da Misericórdia");

        jScrollPane11.setViewportView(jListProdutosRestauranteH);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/118.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setMaximumSize(new java.awt.Dimension(111, 41));
        btnCancel.setMinimumSize(new java.awt.Dimension(111, 41));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014" }));

        jBtnPesquisa.setText("Pesquisa");
        jBtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaActionPerformed(evt);
            }
        });

        jLabel8.setText("Restaurante “Champanheria”");

        jScrollPane5.setViewportView(jListProdutosRestauranteC);

        jLabel15.setText("Restaurante “Malagueta”");

        jScrollPane10.setViewportView(jListProdutosRestauranteF);

        jLabel19.setText("TOTAL ANO");

        jScrollPane12.setViewportView(jListProdutosRestauranteTotais);

        jLabel17.setText("DATA:");

        jLabelData.setText("88-88.8888");

        jLabel18.setText("Semana:");

        jLabelSemana.setText("jLabel17");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/77.png"))); // NOI18N
        jLabel20.setText("Pré-Encomenda");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel20)))
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisa)
                                .addGap(314, 314, 314)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabelSemana)
                    .addComponent(jLabel20))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel16)
                                .addComponent(jLabel14))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPesquisa))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:

        closeApplication();


    }//GEN-LAST:event_btnCancelActionPerformed

    private void jBtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaActionPerformed
        // TODO add your handling code here:
        ano=Integer.parseInt((String)jComboBoxAno.getSelectedItem());
        DoConnect();
    }//GEN-LAST:event_jBtnPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPreEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListaPreEncomendas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jBtnPesquisa;
    private javax.swing.JComboBox jComboBoxAno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelSemana;
    private javax.swing.JList jListProdutosRestauranteA;
    private javax.swing.JList jListProdutosRestauranteB;
    private javax.swing.JList jListProdutosRestauranteC;
    private javax.swing.JList jListProdutosRestauranteD;
    private javax.swing.JList jListProdutosRestauranteE;
    private javax.swing.JList jListProdutosRestauranteF;
    private javax.swing.JList jListProdutosRestauranteG;
    private javax.swing.JList jListProdutosRestauranteH;
    private javax.swing.JList jListProdutosRestauranteTotais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void closeApplication() {
        dispose();
    }

    private void DoConnect() {
        try {
            String host = "jdbc:mysql://localhost:3306/"+dbName;
            String uName = "root";
            String uPass ="admin";
            con = DriverManager.getConnection(host, uName, uPass);
            
            stmt = con.createStatement();
            
            DefaultListModel modelRestauranteA = new DefaultListModel(); //create a new list model
            DefaultListModel modelRestauranteB = new DefaultListModel();
            DefaultListModel modelRestauranteC = new DefaultListModel();
            DefaultListModel modelRestauranteD = new DefaultListModel();
            DefaultListModel modelRestauranteE = new DefaultListModel();
            DefaultListModel modelRestauranteF = new DefaultListModel();
            DefaultListModel modelRestauranteG = new DefaultListModel();
            DefaultListModel modelRestauranteH = new DefaultListModel();
            DefaultListModel modelRestauranteTotais = new DefaultListModel();
            
            
            //Restaurante 1
            String sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=1 and "+dbName+".pre_encomenda.ano='" + ano +"'";
            
           
            ResultSet rsProdutosRestauranteA1;
            
            rsProdutosRestauranteA1 = stmt.executeQuery(sql1);
            
                     
            
            int linha=0,j;
            
            rsProdutosRestauranteA1.last();
           
            RAItemList= new String[rsProdutosRestauranteA1.getRow()];
            RAItemList2= new Integer[rsProdutosRestauranteA1.getRow()];
            
           
            rsProdutosRestauranteA1.beforeFirst();
            rsProdutosRestauranteA1.next();
            
            
    
            //date2 = rsProdutosRestauranteA1.getDate("pre_encomenda.ano");
             
            //Integer ano2 = date2.getYear()+1900;
             
            // System.out.println("data1: " + ano);
            // System.out.println("data2: " + ano2);
             
            boolean control;
            rsProdutosRestauranteA1.beforeFirst();
            while (rsProdutosRestauranteA1.next()){ 
               control=false;
               for(j=0;j<RAItemList.length;j++)  {
                    if (rsProdutosRestauranteA1.getString("produtos.nome").equals(RAItemList[j]) && rsProdutosRestauranteA1.getInt("pre_encomenda.quantidade")!=0) {
                            RAItemList2[j] = RAItemList2[j] + rsProdutosRestauranteA1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteA1.getInt("pre_encomenda.quantidade")!=0) {
                    RAItemList[linha] = rsProdutosRestauranteA1.getString("produtos.nome"); //get the element in column "item_code"
                    RAItemList2[linha] = rsProdutosRestauranteA1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteA.addElement(RAItemList[j] + " - " + RAItemList2[j].toString()); 
            
            jListProdutosRestauranteA.setModel(modelRestauranteA);
            
           
           //Restaurante 2
           sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=2 and "+dbName+".pre_encomenda.ano='" + ano +"'";
            ResultSet rsProdutosRestauranteB1;
            
            rsProdutosRestauranteB1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteB1.last();
           
            RBItemList= new String[rsProdutosRestauranteB1.getRow()];
            RBItemList2= new Integer[rsProdutosRestauranteB1.getRow()];
            
            rsProdutosRestauranteB1.next();
            rsProdutosRestauranteB1.beforeFirst();
            
            while (rsProdutosRestauranteB1.next()){ 
               control=false;
               for(j=0;j<RBItemList.length;j++)  {
                    if (rsProdutosRestauranteB1.getString("produtos.nome").equals(RBItemList[j]) && rsProdutosRestauranteB1.getInt("pre_encomenda.quantidade")!=0) {
                            RBItemList2[j] = RBItemList2[j] + rsProdutosRestauranteB1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteB1.getInt("pre_encomenda.quantidade")!=0) {
                    RBItemList[linha] = rsProdutosRestauranteB1.getString("produtos.nome"); //get the element in column "item_code"
                    RBItemList2[linha] = rsProdutosRestauranteB1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
           
            }
           for(j=0;j<linha;j++)  
               modelRestauranteB.addElement(RBItemList[j] + " - " + RBItemList2[j].toString()); 
            
            jListProdutosRestauranteB.setModel(modelRestauranteB);
           
           //Restaurante 3
           sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=3 and "+dbName+".pre_encomenda.ano='" + ano +"'";
            ResultSet rsProdutosRestauranteC1;
            
            rsProdutosRestauranteC1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteC1.last();
           
            RCItemList= new String[rsProdutosRestauranteC1.getRow()];
            RCItemList2= new Integer[rsProdutosRestauranteC1.getRow()];
            
            rsProdutosRestauranteC1.next();
            rsProdutosRestauranteC1.beforeFirst();
            
            while (rsProdutosRestauranteC1.next()){ 
               control=false;
               for(j=0;j<RCItemList.length;j++)  {
                    if (rsProdutosRestauranteC1.getString("produtos.nome").equals(RCItemList[j]) && rsProdutosRestauranteC1.getInt("pre_encomenda.quantidade")!=0) {
                            RCItemList2[j] = RCItemList2[j] + rsProdutosRestauranteC1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteC1.getInt("pre_encomenda.quantidade")!=0) {
                    RCItemList[linha] = rsProdutosRestauranteC1.getString("produtos.nome"); //get the element in column "item_code"
                    RCItemList2[linha] = rsProdutosRestauranteC1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteC.addElement(RCItemList[j] + " - " + RCItemList2[j].toString()); 
            
            jListProdutosRestauranteC.setModel(modelRestauranteC);
            
          //Restaurante 4
           sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=4 and "+dbName+".pre_encomenda.ano='" + ano +"'";
             ResultSet rsProdutosRestauranteD1;
            
            rsProdutosRestauranteD1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteD1.last();
           
            RDItemList= new String[rsProdutosRestauranteD1.getRow()];
            RDItemList2= new Integer[rsProdutosRestauranteD1.getRow()];
            
            rsProdutosRestauranteD1.next();
            rsProdutosRestauranteD1.beforeFirst();
            
            while (rsProdutosRestauranteD1.next()){ 
               control=false;
               for(j=0;j<RDItemList.length;j++)  {
                    if (rsProdutosRestauranteD1.getString("produtos.nome").equals(RDItemList[j]) && rsProdutosRestauranteD1.getInt("pre_encomenda.quantidade")!=0) {
                            RDItemList2[j] = RDItemList2[j] + rsProdutosRestauranteD1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteD1.getInt("pre_encomenda.quantidade")!=0) {
                    RDItemList[linha] = rsProdutosRestauranteD1.getString("produtos.nome"); //get the element in column "item_code"
                    RDItemList2[linha] = rsProdutosRestauranteD1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteD.addElement(RDItemList[j] + " - " + RDItemList2[j].toString()); 
            
            jListProdutosRestauranteD.setModel(modelRestauranteD);
            
           //Restaurante 5
           sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=5 and "+dbName+".pre_encomenda.ano='" + ano +"'";
            ResultSet rsProdutosRestauranteE1;
            
            rsProdutosRestauranteE1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteE1.last();
           
            REItemList= new String[rsProdutosRestauranteE1.getRow()];
            REItemList2= new Integer[rsProdutosRestauranteE1.getRow()];
            
           
            
           rsProdutosRestauranteE1.next();
            rsProdutosRestauranteE1.beforeFirst();
            
            while (rsProdutosRestauranteE1.next()){ 
               control=false;
               for(j=0;j<REItemList.length;j++)  {
                    if (rsProdutosRestauranteE1.getString("produtos.nome").equals(REItemList[j]) && rsProdutosRestauranteE1.getInt("pre_encomenda.quantidade")!=0) {
                            REItemList2[j] = REItemList2[j] + rsProdutosRestauranteE1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteE1.getInt("pre_encomenda.quantidade")!=0) {
                    REItemList[linha] = rsProdutosRestauranteE1.getString("produtos.nome"); //get the element in column "item_code"
                    REItemList2[linha] = rsProdutosRestauranteE1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteE.addElement(REItemList[j] + " - " + REItemList2[j].toString()); 
            
            jListProdutosRestauranteE.setModel(modelRestauranteE);
            
            //Restaurante 6
           sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=6 and "+dbName+".pre_encomenda.ano='" + ano +"'";
             ResultSet rsProdutosRestauranteF1;
            
            rsProdutosRestauranteF1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteF1.last();
           
            RFItemList= new String[rsProdutosRestauranteF1.getRow()];
            RFItemList2= new Integer[rsProdutosRestauranteF1.getRow()];
            
            rsProdutosRestauranteF1.next();
            rsProdutosRestauranteF1.beforeFirst();
            
            while (rsProdutosRestauranteF1.next()){ 
               control=false;
               for(j=0;j<RFItemList.length;j++)  {
                    if (rsProdutosRestauranteF1.getString("produtos.nome").equals(RFItemList[j]) && rsProdutosRestauranteF1.getInt("pre_encomenda.quantidade")!=0) {
                            RFItemList2[j] = RFItemList2[j] + rsProdutosRestauranteF1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteF1.getInt("pre_encomenda.quantidade")!=0) {
                    RFItemList[linha] = rsProdutosRestauranteF1.getString("produtos.nome"); //get the element in column "item_code"
                    RFItemList2[linha] = rsProdutosRestauranteF1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteF.addElement(RFItemList[j] + " - " + RFItemList2[j].toString()); 
            
            jListProdutosRestauranteF.setModel(modelRestauranteF);
            
         //Restaurante 7
             sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=7 and "+dbName+".pre_encomenda.ano='" + ano +"'";
            
            ResultSet rsProdutosRestauranteG1;
            
            rsProdutosRestauranteG1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteG1.last();
           
            RGItemList= new String[rsProdutosRestauranteG1.getRow()];
            RGItemList2= new Integer[rsProdutosRestauranteG1.getRow()];
            
            rsProdutosRestauranteG1.next();
            rsProdutosRestauranteG1.beforeFirst();
            
            while (rsProdutosRestauranteG1.next()){ 
               control=false;
               for(j=0;j<RGItemList.length;j++)  {
                    if (rsProdutosRestauranteG1.getString("produtos.nome").equals(RGItemList[j]) && rsProdutosRestauranteG1.getInt("pre_encomenda.quantidade")!=0) {
                            RGItemList2[j] = RGItemList2[j] + rsProdutosRestauranteG1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteG1.getInt("pre_encomenda.quantidade")!=0) {
                    RGItemList[linha] = rsProdutosRestauranteG1.getString("produtos.nome"); //get the element in column "item_code"
                    RGItemList2[linha] = rsProdutosRestauranteG1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteG.addElement(RGItemList[j] + " - " + RGItemList2[j].toString()); 
            
            jListProdutosRestauranteG.setModel(modelRestauranteG);
            
            //Restaurante 8
           sql1 = "select "+dbName+".produtos.nome, "+dbName+".pre_encomenda.quantidade from "+dbName+".produtos "
                    + "INNER JOIN "+dbName+".pre_encomenda ON "+dbName+".produtos.idprodutos="+dbName+".pre_encomenda.produtos_idprodutos "
                    + "WHERE "+dbName+".pre_encomenda.restaurantes_idrestaurantes=8 and "+dbName+".pre_encomenda.ano='" + ano +"'";
            ResultSet rsProdutosRestauranteH1;
            
            rsProdutosRestauranteH1 = stmt.executeQuery(sql1);
            
        
            
            linha=0;
            
            rsProdutosRestauranteH1.last();
           
            RHItemList= new String[rsProdutosRestauranteH1.getRow()];
            RHItemList2= new Integer[rsProdutosRestauranteH1.getRow()];
            
            rsProdutosRestauranteH1.next();
            rsProdutosRestauranteH1.beforeFirst();
            
            while (rsProdutosRestauranteH1.next()){ 
               control=false;
               for(j=0;j<RHItemList.length;j++)  {
                    if (rsProdutosRestauranteH1.getString("produtos.nome").equals(RHItemList[j]) && rsProdutosRestauranteH1.getInt("pre_encomenda.quantidade")!=0) {
                            RHItemList2[j] = RHItemList2[j] + rsProdutosRestauranteH1.getInt("pre_encomenda.quantidade");
                             control=true;
                            break;
                    }
               }
               if (control==false && rsProdutosRestauranteH1.getInt("pre_encomenda.quantidade")!=0) {
                    RHItemList[linha] = rsProdutosRestauranteH1.getString("produtos.nome"); //get the element in column "item_code"
                    RHItemList2[linha] = rsProdutosRestauranteH1.getInt("pre_encomenda.quantidade"); //get the element in column "item_code"
                    linha++;
               }              
            }
           for(j=0;j<linha;j++)  
               modelRestauranteH.addElement(RHItemList[j] + " - " + RHItemList2[j].toString()); 
            
            jListProdutosRestauranteH.setModel(modelRestauranteH);
            
           //Totais
           sql1 = "select * from produtos ";
            
           ResultSet rsProdutosTotais;
            
           rsProdutosTotais = stmt.executeQuery(sql1);
           
            
           rsProdutosTotais.last();
           
            
                            
            totalProdutos=rsProdutosTotais.getRow(); 
            //totalRestaurantes=rsProdutosTotais.getRow();
            totalNomesProdutos = new String[rsProdutosTotais.getInt(1)];
            totalQuantidadeProdutos = new Integer[rsProdutosTotais.getInt(1)];
            for(j=0;j<totalProdutos;j++)  {
                totalNomesProdutos[j] = " ";
                totalQuantidadeProdutos[j] = 0;
            }
            
          linha=0;
          for (int i=0;i<modelRestauranteA.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RAItemList[i])) {
                            totalQuantidadeProdutos[j] = RAItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RAItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RAItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          
          
         for (int i=0;i<modelRestauranteB.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RBItemList[i])) {
                            totalQuantidadeProdutos[j] = RBItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RBItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RBItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          for (int i=0;i<modelRestauranteC.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RCItemList[i])) {
                            totalQuantidadeProdutos[j] = RCItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RCItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RCItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          
         for (int i=0;i<modelRestauranteD.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RDItemList[i])) {
                            totalQuantidadeProdutos[j] = RDItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RDItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RDItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          for (int i=0;i<modelRestauranteE.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(REItemList[i])) {
                            totalQuantidadeProdutos[j] = REItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = REItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = REItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          for (int i=0;i<modelRestauranteF.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RFItemList[i])) {
                            totalQuantidadeProdutos[j] = RFItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RFItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RFItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          for (int i=0;i<modelRestauranteG.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RGItemList[i])) {
                            totalQuantidadeProdutos[j] = RGItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RGItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RGItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          for (int i=0;i<modelRestauranteH.size();i++){
                control=false;
               for(j=0;j<totalProdutos;j++)  {
                    if (totalNomesProdutos[j].equals(RHItemList[i])) {
                            totalQuantidadeProdutos[j] = RHItemList2[i] + totalQuantidadeProdutos[j];
                            control=true;
                            break;
                    }
               }
               if (control==false) {
                   totalNomesProdutos[linha] = RHItemList[i]; //get the element in column "item_code"
                   totalQuantidadeProdutos[linha] = RHItemList2[i]; //get the element in column "item_code"
                    linha++;
               }
          
          }
          for(j=0;j<totalProdutos;j++)  {
              if (totalQuantidadeProdutos[j]!=0)
              modelRestauranteTotais.addElement(totalNomesProdutos[j] + " - " +  totalQuantidadeProdutos[j].toString()); 
          }
              
               
            
           jListProdutosRestauranteTotais.setModel(modelRestauranteTotais);
            
            
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(ListaPreEncomendas.this, err.getMessage());
        }
    }
}
